### ISSUE TITLE
Create directories recursively

### ISSUE THREAD

**Issue by curioswati-zz** [eduardoboucas/staticman#1]
I suggest it should be:
    `mkdir -p ${COMMENTS_DIR}` 

here:
https://github.com/eduardoboucas/jekyll-discuss/blob/master/new-comment.sh#L72

**Comment by eduardoboucas** [comment]
I haven't had much time to maintain this project recently. Do you want to send a PR?

**Comment by curioswati-zz** [comment]
oh yes, I will.
