### ISSUE TITLE
No pull requests

### ISSUE THREAD

**Issue by donquant** [eduardoboucas/staticman#100]
Staticman stopped sending pull requests after I deleted old repo and created new [one](https://github.com/donquant/donquant.github.io) with the same name. 

What may be wrong?

**Comment by eduardoboucas** [comment]
You'll need to repeat Step 1 of the documentation on the new repository: https://staticman.net/docs/

**Comment by donquant** [comment]
@eduardoboucas I did it. No success :(

**Comment by eduardoboucas** [comment]
Do you get any errors?

**Comment by donquant** [comment]
@eduardoboucas Nothing. I submitted a comment and got nothing back.

**Comment by donquant** [comment]
I also deleted staticman as collaborator and added it again, than I got an application error after step 1

**Comment by eduardoboucas** [comment]
Can you remove the `reCaptcha` block from your Staticman config file and try again?

Also, can you be a bit more specific on "I got an application error after step 1"? Where exactly and what error? I've just pinged the `/connect` endpoint with your repository and it seems to work.

**Comment by donquant** [comment]
Removing reCaptcha block indeed resolved the issue. Is there some conflict with reCaptcha or is it just me messing something up?

**Comment by eduardoboucas** [comment]
Any issues with reCaptcha should be fixed in the latest release. If you still encounter any problems, please reopen this issue.

Thanks!
