### ISSUE TITLE
Submit comments as issues in github repo rather than as a seperate files in branch?

### ISSUE THREAD

**Issue by schickimiki** [eduardoboucas/staticman#102]
First of all thank for this very useful application with superpowers!

Why I think an option of storing comments as issues on Github would also be useful:
- Ability to handle a comment as an actual issue by reacting with a feature update or bug fix and closing the issue.
- Viewing single comments on github when they are stored as content in files pushed to a branch is not very user friendly. If the comments would be stored as issues then they can be viewed directly on the github issues page.

**Comment by eduardoboucas** [comment]
Thanks for submitting this, but I don't want to broaden the scope and complexity of the platform by introducing this feature.
