### ISSUE TITLE
Stuck at Install Step 1

### ISSUE THREAD

**Issue by Kraymer** [eduardoboucas/staticman#103]
I added `staticmanapp` as collaborator for my [jekyll blog](https://github.com/Kraymer/kraymer.github.com/).
When I open <https://api.staticman.net/v2/connect/kraymer/kraymer.github.com> I have :

<img width="484" alt="application_error" src="https://cloud.githubusercontent.com/assets/84227/25776574/e6ca6c46-32c1-11e7-913c-734a1d4c8e15.png">

PS: big fan of your blog *hot from the press* design and "Listen to this post" feature <3

**Comment by meygerjos** [comment]
I think this will work if you
1. Change the name of your repository to `Kraymer.github.io`
2. Open `https://api.staticman.net/v2/connect/Kraymer/Kraymer.github.io`.

Actually not sure...

**Comment by Kraymer** [comment]
Yeah managed to mek it work yesterday it was indeed the case sensitivity that trapped me.
