### ISSUE TITLE
Is it possible to list the number of comments for a post?

### ISSUE THREAD

**Issue by Hund** [eduardoboucas/staticman#109]
It would be nice if I could have the the title "1 Comment" and "2 Comments" instead of the static title "Comments". It would also be nice if I could show the comments next to the date on the front page as well.

Is this possible? I found no documentation on your website.

**Comment by eduardoboucas** [comment]
This is something you'd do on your static site generator, not something Staticman would handle (we just process the submissions). You can see an example of this working on my site (https://eduardoboucas.com), and you can see the source for it [here](https://github.com/eduardoboucas/eduardoboucas.github.io/blob/master/_includes/partials/post-meta-comment-count.html).

Hope it helps.

**Comment by Hund** [comment]
Ah! Thanks. :)
