### ISSUE TITLE
Redirect after POST

### ISSUE THREAD

**Issue by quicoto** [eduardoboucas/staticman#11]
Correct me if I'm wrong but at the moment you can only implement this via AJAX, right?

How hard would it be to redirect to the page that send the POST or any page for that matter? Maybe we could have a hidden input field with a URL. Then redirect to that URL after the comment has been submitted.

Thank you.

**Comment by eduardoboucas** [comment]
Agree, this makes sense. Will look into it shortly.

**Comment by eduardoboucas** [comment]
This has been implemented by #15.

You can specify a redirect URL like this:

``` html
<input type="hidden" name="options[redirect]" value="http://your-url.com">
```

Let me know of any issues.

**Comment by quicoto** [comment]
It works, thank you!

**Comment by eduardoboucas** [comment]
Added to docs in https://github.com/eduardoboucas/staticman.net/commit/045f5354fba6adf6383be19e2c8922fced8fb74f. Closing!
