### ISSUE TITLE
How to use jekyll with staticman on a server?

### ISSUE THREAD

**Issue by mittalyashu** [eduardoboucas/staticman#113]
What if do not want to use Github Pages, then to make staticman work with Jekyll on a server?

**Comment by eduardoboucas** [comment]
You don't need to use GitHub Pages at all, the only requirement for Staticman to work is that you have a GitHub repository. The service receives form requests and pushes them as flat files to your repo. What you then do with the contents of that repo — whether you serve it with GitHub Pages, Netlify or any other way —  is entirely up to you.

**Comment by mittalyashu** [comment]
If the repo is on GitHub Pages, then how we can access it on any other server?
