### ISSUE TITLE
Is there a Staticman version or equivalent for BitBucket repos?

### ISSUE THREAD

**Issue by deepfriedbrain** [eduardoboucas/staticman#138]
I have been using Staticman with a public repo on GitHub for my Jekyll blog. I need to move my repo to BitBucket in order make use of private repos. Is there a Staticman version or equivalent option for BitBucket repos? 

Thanks!

**Comment by rishabh9** [comment]
+1. I too need this option.

**Comment by eduardoboucas** [comment]
I'm afraid not, sorry. Using different providers (like GitLab, see #22) is something that people have been very interested in, but I just don't have the capacity to build that at the moment.

**Comment by rishabh9** [comment]
How about providing directions to achieve the same? 😁 I would like to give it a try in my spare time.

**Comment by eduardoboucas** [comment]
Well, in theory you should be able to make Staticman work with BitBucket (or any other provider) by re-implementing [this library](https://github.com/eduardoboucas/staticman/blob/master/lib/GitHub.js) in such a way that it reads files, writes files and creates pull requests using BitBucket's API instead.

That's where I'd start.

**Comment by canmetan** [comment]
Writing from 2022, I would also love to have staticman for Bitbucket for private repos.
