### ISSUE TITLE
Feature Requests: Multiple Object Types + Managing Posted Files (by deleting or moving)

### ISSUE THREAD

**Issue by casually-creative** [eduardoboucas/staticman#146]
Didn't really know how to label this as feature request so I'll just write this as an issue.

My first request is to be able to use staticman for more than 1 object. For example I want to use staticman to post comments but also to post reviews or something else. (These are just examples) Right now the staticman.yml only works for 1, there's no way to add a 2nd type of file with a different configuration.

My 2nd request is to be able to manage the content posted via staticman. I would like to implement a management system (not using the built-in one via githubs pull requests). I post files to a "pending" folder and I want moderators to be able to sift through these files on a designated page and either approve or decline. So I'd want to be able to 1: move a certain file (approve) and 2: delete a certain file (decline). I don't want to use the pull request system because I want all our moderation happening on our site and not on github.

I would greatly appreciate it if these 2 features would be implemented!
Thanks!

**Comment by maxime-michel** [comment]
I'm not an authority at all around here, but I'd say:

1. are you sure you can't have multiple objects? You might have tried it already but the first lines of the sample file, which I happen to have read a few times today, seem to indicate you can: https://github.com/eduardoboucas/staticman/blob/master/staticman.sample.yml

2. I think it's unlikely to see this project grow in the direction you're looking for, however, you could probably leave Staticman in place and build something of your own with the GitHub REST API. You could list PRs in a separate app and merge/decline when your moderators want to. See: https://developer.github.com/v3/pulls/

**Comment by eduardoboucas** [comment]
Thanks for your reply @maxime-michel, you are absolutely right.

[Line 5](https://github.com/eduardoboucas/staticman/blob/master/staticman.sample.yml#L5) of the sample config file defines a `comments` property, which will give you an endpoint like `https://api.staticman.net/v2/entry/{GITHUB USERNAME}/{GITHUB REPOSITORY}/{BRANCH}/comments`. You can add as many as you want, each configured differently and each with its own endpoint.

As for question number 2, I'm afraid that's beyond the scope of this project. Maybe you're looking for something like [Netlify CMS](https://github.com/netlify/netlify-cms)?

I'm closing, but feel free to reopen if you have any further questions. Thanks!
