### ISSUE TITLE
ERROR_PROCESSING_ENTRY suddenly

### ISSUE THREAD

**Issue by lisandroct** [eduardoboucas/staticman#159]
Hi! My comments were working just fine and I suddenly got "{success: false, errorCode: "ERROR_PROCESSING_ENTRY"}" as a response every time.

As you can see at https://github.com/lisandroct/lisandroct.github.io/commits/master, the code hasn't changed at all since last time it worked: commit **c934cae7febe45da20ad9ddf188ce6e80e04ac20** was a new comment made by Staticman and after it I only changed style things and a not related javascript.

The comments can be tested at http://lisandroct.com.

Thanks!

**Comment by eduardoboucas** [comment]
Can you try disabling reCaptcha temporarily and seeing if the error persists?

**Comment by lisandroct** [comment]
Thank you for the quick response. Now it's disabled and it still doesn't work. I've pushed it, so you can test it too.

Thanks again!

**Comment by justinrummel** [comment]
Same issues for me.  reCaptcha is still enabled.

``` json
{
    "success": false,
    "errorCode": "ERROR_PROCESSING_ENTRY"
}
```

**Comment by eduardoboucas** [comment]
Bare with me, I'm looking into the issue now.

**Comment by eduardoboucas** [comment]
@lisandroct Your comments are now coming through: https://github.com/lisandroct/lisandroct.github.io/commit/90e12a41f93867d54e10c3ef852c4de808dae3ed

@justinrummel I don't know the URL to your blog, can you please check again to see if the issue persists?

**Comment by justinrummel** [comment]
@eduardoboucas thanks for the quick replies!  I'm still getting the error: 

`Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500)` 

with the same error message `ERROR_PROCESSING_ENTRY`.

article for test comments: [www.justinrummel.com](https://www.justinrummel.com/macworld-2010-pictures/)

**Comment by eduardoboucas** [comment]
@justinrummel Can you try now?

**Comment by justinrummel** [comment]
Fixed, thanks!

**Comment by lisandroct** [comment]
I enabled reCaptcha back again and it works! Thanks!
