### ISSUE TITLE
Override text sent in email subscription

### ISSUE THREAD

**Issue by binarymist** [eduardoboucas/staticman#173]
Just wondering if you would be open to adding functionality to override the text sent in email when a PR is accepted
`Someone replied to a comment you subscribed to`
In https://github.com/eduardoboucas/staticman/blob/master/lib/Notification.js

When the first commenter subscribes, it doesn't really make sense for them to receive an email telling them: `Someone replied to a comment you subscribed to`
It would make more sense and be generic enough also if it were something like:
`Someone commented on a page you subscribed to`

Any chance of providing overrides, or at would you accept a PR to change this text?

Thanks.

**Comment by eduardoboucas** [comment]
Sorry for the delay.

Being able to customise the text sounds ideal, but perhaps as a first approach we could simply change the default text? Happy to look at a PR.

Thanks!

**Comment by binarymist** [comment]
Ok, is the proposed text acceptable?
