### ISSUE TITLE
Spam everyday, another way to filter than Akismet?

### ISSUE THREAD

**Issue by ghost** [eduardoboucas/staticman#175]
Hi, I want to know what method is recommended to avoid spammers... My site is in Spanish, and everyday I receive a comment for polish people, and no related to my post... I have the honey pot (hope correctly), and Akismet it's no avalaible to my blog... Is another system to filter spam?

**Comment by ulisesac4** [comment]
You can use Recaptcha:

*https://recaptcha-demo.staticman.net/
*https://github.com/eduardoboucas/staticman-recaptcha

I have not been able to use it, but it seems really good.

**Comment by ghost** [comment]
Thanks, I used it, but sometimes was a problem of loading... I simply eliminate the url field... No problem for a week, I hope this continue
