### ISSUE TITLE
(Feature request) Email notifications with moderation disabled

### ISSUE THREAD

**Issue by rjtngit** [eduardoboucas/staticman#177]
Hi

First, I love Staticman - it's awesome. I'm using it with the Minimal Mistakes Jekyll template which is also awesome.

I like getting an email notification when Staticman submits a pull request. As far as I know, there's no way to subscribe to email notifications for commits/pushes to a GitHub repo, which means email notifications don't work with moderation disabled. You can, however, subscribe to email notifications for comments on commits. 

Have you thought about having Staticman comment on its commits if moderation is disabled?

**Comment by eduardoboucas** [comment]
Hi! Thanks for your kind words.

I understand your use case, but I think it falls outside the scope of the project. Perhaps you could look into adding a [webhook](https://developer.github.com/webhooks/) to your repository, which would use some third-party service to email you when there is a new commit?

Hope this helps.

**Comment by rjtngit** [comment]
Hey, thanks, I just found this which is exactly what I'm looking for:

https://help.github.com/articles/choosing-the-types-of-notifications-you-receive/#enabling-email-service-notifications-for-pushes-to-your-repository
