### ISSUE TITLE
(Feature request) Conditional moderation 

### ISSUE THREAD

**Issue by rjtngit** [eduardoboucas/staticman#178]
I like having moderation off by default because a) I am lazy and b) I trust most of my readers/commenters to be cool. 

It would be nice if I could set up some word filters which would cause Staticman to use a pull request. For example, admin names and email addresses, profanity filters, etc. 

Would it even be possible to implement something like this?

**Comment by eduardoboucas** [comment]
It would be possible, yes, but given the complexity of the feature and its configuration possibilities and the amount of time I have to dedicate to building and maintaining the project at present, I don't think this is feasible in the foreseeable future.

In any case, thanks for the suggestion! Much appreciated.
