### ISSUE TITLE
staticmanapp collaboration invitation

### ISSUE THREAD

**Issue by JOJ0** [eduardoboucas/staticman#180]
Hi Eduardo,
I am trying to give your public staticman instance a try. I am following your guide: https://staticman.net/docs/

In step 1 it tells my to share my websites repo with the staticmanapp user. which i did, it is now stating "awaiting staticmanapp's response"

the guide tells me to open this url:
https://api.staticman.net/v2/connect/{your GitHub username}/{your repository name}

in my case this would be: https://api.staticman.net/v2/connect/joj0/joj0.github.io
which gives me the error message: "Invitation not found"

Am I missing something? Any hints appreciated!

Thanks 
Jojo

**Comment by JOJ0** [comment]
this is what the settings - collaborators page of my site's repo looks like at the moment:

![screen shot 2018-02-16 at 17 06 43](https://user-images.githubusercontent.com/2733783/36316899-e4133234-133b-11e8-9e34-b36fab1d3b3e.png)

**Comment by IanCaio** [comment]
Your Github username is case sensitive, so your link should be https://api.staticman.net/v2/connect/JOJ0/joj0.github.io instead.

I ended up accepting your invitation when I was testing the link.

**Comment by JOJ0** [comment]
hahaha alright, I was not aware of the case sensitivity. thanks a lot Ian! And thanks for doing all the work for me ;-))
