### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by ghost** [eduardoboucas/staticman#193]
Any change to get I18 for staticman?

**Comment by matbrgz** [comment]
How could I help to implement this?

**Comment by VincentTam** [comment]
Staticman's job is to transmit HTML form data into Git repo, so this is not an issue of Staticman.  You may find the YAML files in `i18n` in any static blog themes like Minimal Mistakes or [Beautiful Hugo](https://github.com/halogenica/beautifulhugo).
