### ISSUE TITLE
Encrypt with my key

### ISSUE THREAD

**Issue by aquilesC** [eduardoboucas/staticman#196]
I would like to be able to use the e-mails of the people submitting messages, but not to make them public in my repository. 
Is there any way of encrypting different fields of the form with my own public key, in order to retrieve them at a later stage?

**Comment by StephenCleary** [comment]
Dup of https://github.com/eduardoboucas/staticman/issues/168?

**Comment by binarymist** [comment]
Sounds like it.

**Comment by aquilesC** [comment]
It is.
