### ISSUE TITLE
Error 404 and other, anyone can help me 

### ISSUE THREAD

**Issue by artipedia** [eduardoboucas/staticman#197]
anyone can help me fix this kind of mistake?

```
{"success":false,"rawError":{"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/contents/#get-contents\"}"},"errorCode":"GITHUB_READING_FILE"}
```

https://github.com/ArtiPedia/ArtiPedia/blob/master/docs/_config.yml
https://github.com/ArtiPedia/ArtiPedia/blob/master/docs/staticman.yml

thank you for your help

**Comment by sanderjson** [comment]
What was your solution to this? I am having the same issue

**Comment by artipedia** [comment]
copy this configuration and then change "messages" to "message", https://rawgit.com/ArtiPedia/ArtiPedia/master/staticman.yml

**Comment by sanderjson** [comment]
I am getting the same error. 

`CONFIG:
comments:
  allowedFields: ["name", "email", "message"]
  allowedOrigins: ["localhost", "heuristic-lalande-8c9f8f.netlify.com"]
  branch: "master"
  commitMessage: "Add Staticman data"
  filename: "entry{@timestamp}"
  format: "yaml"
  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-seconds"
  moderation: true
  name: "Thriving Cities"
  path: "_data/comments/{options.slug}"
  requiredFields: ["name", "email", "message"]
  transforms:
    email: md5

PARTIAL: 
  <form class="post-new-comment" method="POST" action="https://dev.staticman.net/v2/entry/jSwtch/thriving-cities-events/master/comments">
    <input type="hidden" name="options[redirect]" value="{{ .Permalink }}#comment-submitted">
    <input type="hidden" name="options[entryId]" value="{{ .UniqueID }}">
    <input name="fields[name]" type="text" class="post-comment-field" placeholder="Your name">
    <input name="fields[email]" type="email" class="post-comment-field" placeholder="Your email address">
    <textarea name="fields[message]" class="post-comment-field" placeholder="Your message. Feel free to use Markdown." rows="10"></textarea>
    <input type="submit" class="post-comment-field btn" value="Submit">
  </form>`

**Comment by jSwtch** [comment]
PARTIAL: 
  <form class="post-new-comment" method="POST" action="https://dev.staticman.net/v2/entry/jSwtch/thriving-cities-events/master/comments">
    <input type="hidden" name="options[redirect]" value="{{ .Permalink }}#comment-submitted">
    <input type="hidden" name="options[entryId]" value="{{ .UniqueID }}">
    <input name="fields[name]" type="text" class="post-comment-field" placeholder="Your name">
    <input name="fields[email]" type="email" class="post-comment-field" placeholder="Your email address">
    <textarea name="fields[message]" class="post-comment-field" placeholder="Your message. Feel free to use Markdown." rows="10"></textarea>
    <input type="submit" class="post-comment-field btn" value="Submit">
  </form>`

**Comment by artipedia** [comment]
Yes me to..

And then i try copy configuration on raw files (url above) problem solved. 

You must try copy all code (from url above)

**Comment by artipedia** [comment]
Not copy on github.

**Comment by artipedia** [comment]
Can you share your github url?

**Comment by sanderjson** [comment]
https://github.com/jSwtch/thriving-cities-events

**Comment by artipedia** [comment]
try move staticman file to front
