### ISSUE TITLE
GITHUB_READING_FILE

### ISSUE THREAD

**Issue by sanderjson** [eduardoboucas/staticman#202]
I have read report from others, and I have checked for all the common errors (mispelled staticman.yml, v1 vs v2 entry point, optional 'comments' in the URL). I am still getting this GITHUB_READING_FILE error.

Any help would be appreciated,

Repo: https://github.com/jSwtch/thriving-cities-events
Config: https://github.com/jSwtch/thriving-cities-events/blob/master/site/staticman.yml
Partial: https://github.com/jSwtch/thriving-cities-events/blob/master/site/layouts/partials/comments-form.html

I referenced the config from: https://github.com/eduardoboucas/hugo-plus-staticman/blob/master/staticman.yml and the partial from https://github.com/eduardoboucas/hugo-plus-staticman/blob/master/themes/hugo-type-theme/layouts/partials/post-comments.html

**Comment by tsalik** [comment]
Hi! 

Have you pushed your staticman.yml file to the appropriate branch? I had the same problem with yours  and when I pushed the staticman configuration it worked perfectly. Check this [ issue](https://github.com/eduardoboucas/staticman/issues/130) for reference.

**Comment by alexwaibel** [comment]
@jSwtch were you able to resolve this?

**Comment by sanderjson** [comment]
@alexwaibel I did not resolve this. It is likely that tsalik comment is appropriate. I will close the issue.
