### ISSUE TITLE
Travis node eslint build errors

### ISSUE THREAD

**Issue by donaldboulton** [eduardoboucas/staticman#206]
Build errors on master and dev for a while now since commit 376243b on master
Also the same day as minimal mistakes stopped working: issue: [183](https://github.com/eduardoboucas/staticman/issues/183)

[Travis build error Commit:](https://github.com/eduardoboucas/staticman/commit/376243bd121f34b7288d0ea2add405714862cdc9)

**Comment by alexwaibel** [comment]
Duplicate of #318
