### ISSUE TITLE
staticman failing to create pull request

### ISSUE THREAD

**Issue by hendrixjoseph** [eduardoboucas/staticman#217]
Steps to reproduce:

* Go to the [Popcorn](http://popcorn.staticman.net/) demo site.
* Enter a review.
* Hit submit.

Result: an error dialog appears ("Error Sorry, there was an error with the submission!")

A new branch will be created, but there will be no pull request. For instance, this is the file in the branch when I tried - https://github.com/eduardoboucas/popcorn/blob/staticman_d5564aa0-86cd-11e8-bce9-2fc4fd410763/_data/reviews/entry1531507924416.yml

I notices this on [my own blog](https://hendrixjoseph.github.io/) as well, but got a more detailed response:

```json
{
   "success":false,
   "rawError":{
      "code":403,
      "status":"Forbidden",
      "message":"{\"message\":\"At least one email address must be verified to do that.\",
           \"documentation_url\":\"https://help.github.com/articles/adding-an-email-address-to-your-github-account\"}"
   },
   "errorCode":"GITHUB_CREATING_PR"
}
```

**Comment by MiKatre** [comment]
Exact same issue with my two websites using staticman:


```
{
   "success":false,
   "rawError":{
      "code":403,
      "status":"Forbidden",
      "message":"{\"message\":\"At least one email address must be verified to do that.\",
           \"documentation_url\":\"https://help.github.com/articles/adding-an-email-address-to-your-github-account\"}"
   },
   "errorCode":"GITHUB_CREATING_PR"
}
```

**Comment by hendrixjoseph** [comment]
I just verified that this is the same error from the Popcorn demo site

```json
{
    "success": false,
    "rawError": {
        "code": 403,
        "status": "Forbidden",
        "message": "{\"message\":\"At least one email address must be verified to do that.\",\"documentation_url\":\"https://help.github.com/articles/adding-an-email-address-to-your-github-account\"}"
    },
    "errorCode": "GITHUB_CREATING_PR"
}
```

is this some change in github's platform, or is there no email associated with staticman?

also, if I go to the GitHub page for @staticmanapp (https://github.com/staticmanapp) I get a 500 server error. it doesn't happen with anyone else's user page

**Comment by nfreear** [comment]
Hi @eduardoboucas,

I see the same issue as reported by @hendrixjoseph and @MiKatre on my blog,

 * https://github.com/nfreear/nfreear.github.io

 * [GitHub docs: adding-an-email-address-to-your-github-account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/)

Yours,

Nick

**Comment by GonzaloZiadi** [comment]
Facing this same issue as well.

**Comment by jloisel** [comment]
:+1: on this. Same issue here.

**Comment by eduardoboucas** [comment]
Something really odd is going on. When I try to sign in to GitHub as staticmanapp (the user account used by the public instance to create the pull requests), I get that 500 page. No additional information whatsoever.

I'll try to find out what's going on, but it's definitely something that changed on the GitHub side.

**Comment by Stanko** [comment]
It seems that bot account has no verified email address set. It is probably security change on the github side. I think verifying email address would probably solve it.

https://help.github.com/articles/verifying-your-email-address/

**Comment by eduardoboucas** [comment]
I thought the email was verified, but apparently that wasn't the case. Anyway, I managed to do this, but I still see a 500 page when I try to access the profile.

Can anyone confirm if the API errors still persist?

Thanks!

**Comment by Stanko** [comment]
@eduardoboucas works here! Thank you for the fast turnaround!  🎉

**Comment by hendrixjoseph** [comment]
all good here. @staticmanapp is no longer showing a 500 error for me either https://github.com/staticmanapp

**Comment by jloisel** [comment]
I confirm it's working on our side too.

**Comment by eduardoboucas** [comment]
Great. Thanks all!
