### ISSUE TITLE
A closed source website in the list of Staticman powered sites

### ISSUE THREAD

**Issue by VincentTam** [eduardoboucas/staticman#234]
A list of sites running Staticman appears in the last section of README.  Almost _all_ of them include a link to their source code, including @zongren 's personal blog.

However, the ([Source](https://gitlab.com/zongren/zongren.gitlab.io/)) link at the right of the entry
- [zongren.me](https://zongren.me)

points to its GitLab project page, which **doesn't** show the source code generating the site.

Proposal:
1. ~([Source](https://gitlab.com/zongren/zongren.gitlab.io/))~; or
2. @zongren publishes the source code and fixes the link.

**Comment by zongren** [comment]
It seems like some config errors,sorry about the mistake,[repository](https://gitlab.com/zongren/zongren.gitlab.io/) is opensourced now.

**Comment by zongren** [comment]
I tested it in chrome private mode
<img width="1463" alt="2018-09-17 5 20 38" src="https://user-images.githubusercontent.com/4525819/45615429-0b7b5a80-ba9f-11e8-876c-04bc247048d0.png">

**Comment by VincentTam** [comment]
@zongren No problem :smile: Thanks for update!

I seize the chance to view your implementation of Staticman.  IMHO,

1. It's better to move site specific config (`staticman`, `recaptcha`, etc) from `themes/hexo-theme-nojs/_config.yml` to the root level site config, for example, [Beautiful Hugo][bh].  (You're more than welcome to checkout [my demo project][demo] and its source for a concrete example.)
2. `themes/hexo-theme-nojs` has better to be a Git submodule, since it's an _independent and portable_ project.  [Hugo]'s quickstart guide recommends downloading themes as Git submodules.

[bh]: https://github.com/halogenica/beautifulhugo
[demo]: https://vincenttam.gitlab.io/test-hugo-staticman/
[Hugo]: https://gohugo.io

**Comment by zongren** [comment]
Thanks for the advice!

**Comment by VincentTam** [comment]
@zongren You're welcome.
