### ISSUE TITLE
Question/Help Needed - Using my own staticman instance and cannot post comments

### ISSUE THREAD

**Issue by SophieAu** [eduardoboucas/staticman#237]
I tried setting up my own staticman instance and I just cannot get it to post comments to my repo.

My bot is here: [https://github.com/impsplen-staticman/staticman](https://github.com/impsplen-staticman/staticman). I just forked the repo and added an empty config file (to get the env vars/defaults). The parameters are passed in through Heroku (Github Token with every box checked, RSA Key, Node env).

Adding the bot as a collaborator worked like a charm but the postting doesn't work. I continuously get this error: `Cannot POST /v2/entry/SophieAu/imperial-splendour-website/master/data/comments`. The response from the server is a 404.

Thingss I've tried/double checked:
* The url is correct and as described in the documentation
* the bot has been added as a collaborator
* the staticman.yml is the default/sample one

Any ideas on what might be going wrong would be very much appreciated .

**Comment by ghost** [comment]
So I got a bit further. I fixed the 404 by changing the url to `/v2/entry/SophieAu/imperial-splendour-website/master/data/` but now I'm getting a `MISSING_CONFIG_BLOCK` error, both when I run it locally and on production. Any ideas?

Sorry, this is me posting as my bot XD

**Comment by SophieAu** [comment]
After a lot of trial and error (I still don't know what the problem was) I finally fixed it...

**Comment by VincentTam** [comment]
It's time to change this to `/v3/entry/github/SophieAu/imperial-splendour-website/master/data/` due to #255.
