### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by shoreviewanalytics** [eduardoboucas/staticman#240]
I've been able to deploy the Staticman API to a Dokku droplet (staticman.shoreviewanalytics.com), but when I add reCaptcha I get an error.  
![internal server error](https://user-images.githubusercontent.com/36421939/48518743-8c08ce00-e838-11e8-81ed-fe4e930cad8d.png)
I'm not sure where the issue is coming from?  What I know is that comments work without reCaptcha. However, when I add reCaptcha the error occurs.

**Comment by shoreviewanalytics-staticman** [comment]
From the droplet if I run. 

curl -v 'https://staticman.shoreviewanalytics.com/v2/entry/shoreviewanalytics/shoreviewanalytics.github.io/master/comments' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://shoreviewanalytics.github.io/Staticman-API-Dokku-Deployment/' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: https://shoreviewanalytics.github.io' -H 'Connection: keep-alive' --data 'fields%5Bmessage%5D=test&fields%5Bname%5D=Chad+Downey&fields%5Bemail%5D=jamochee.one%40gmail.com&fields%5Burl%5D=http%3A%2F%2Fshoreviewanalytics.github.io&options%5Bslug%5D=Staticman-API-Dokku-Deployment&fields%5Bhidden%5D=&options%5BreCaptcha%5D%5BsiteKey%5D=6LdLw3oUAAAAAFYR3DN4tiD-wG1Ca-cNqYB1EkVA&options%5BreCaptcha%5D%5Bsecret%5D=yPYmyCOLRSgjev1ri5kVkIkU2L3OAigynLVBwzAkleQo%2FopyBUBkm%2FRyJFM4OKRI2hM6n3osn7VSQSSxwt5ijRrkd9MJ%2FZKzQ%2FQrLW%2Ffe8LtNQtIFlvXqSjaMSUw94AZ2Cv6edzAv129R%2By2eg13BPnYSxTN9YIvb2fBMjBR76A%3D&g-recaptcha-response=03ADlfD1-o9DfpJ9CSr1ziJAMdoAOiwl9JJgDGKHwYUEoywSiH0uNL5fh-a49StbI1a0HvoBgIMSXgEKiqgDLHrjOU9iavz8G7a2VsUG-DGZWGmi9xMoq-QJANGC9FARoPO18iAoMuoQKnfUGhSDVyTtn4CodNtslV74XRMJ2ymLALK7_motKiMvJQdV8lRl1exQBZtuIRQZaKgDc1-I9w7NrS3ej8YOSvmzENyXLrGAdEOMrFJS5Usks0RTBSM6V97onv6Vngo38OCH9Inr1B3neyqtL_4epzacLVMaQlPKPQP3Bpdz-QZSQGPm14LpccdDTZ4e_7okgF'

I'm able to post the comment.

**Comment by shoreviewanalytics** [comment]
It turns out that I'm not able to post a comment at all when reCaptcha is enabled.  Wondering if the second part in bold is needed in the post?  If it's not there the post works fine.  I've intentionally split the POST up to clarify the split between what works and what doesn't work.  Wondering if this is a code issue for staticman or if a code issue in the Jekyll theme I am using?  

curl 'https://staticman.shoreviewanalytics.com/v2/entry/shoreviewanalytics/shoreviewanalytics.github.io/master/comments' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://shoreviewanalytics.github.io/Staticman-API-Dokku-Deployment/' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: https://shoreviewanalytics.github.io' -H 'Connection: keep-alive' --data 'fields%5Bmessage%5D=testing&fields%5Bname%5D=Chad+Downey&fields%5Bemail%5D=jamochee.one%40gmail.com&fields%5Burl%5D=http%3A%2F%2Fshoreviewanalytics.github.io&options%5Bslug%5D=Staticman-API-Dokku-Deployment&fields%5Bhidden%5D='



**&options%5BreCaptcha%5D%5BsiteKey%5D=6LdLw3oUAAAAAFYR3DN4tiD-wG1Ca-cNqYB1EkVA&options%5BreCaptcha%5D%5Bsecret%5D=yPYmyCOLRSgjev1ri5kVkIkU2L3OAigynLVBwzAkleQo%2FopyBUBkm%2FRyJFM4OKRI2hM6n3osn7VSQSSxwt5ijRrkd9MJ%2FZKzQ%2FQrLW%2Ffe8LtNQtIFlvXqSjaMSUw94AZ2Cv6edzAv129R%2By2eg13BPnYSxTN9YIvb2fBMjBR76A%3D&g-recaptcha-response=03ADlfD1-PL9mc5t3qZhWkrEBTZ9yk0PQkkYkNcW21zzMSzqXOD6AqixRGhaC_Jm-qwr8WhwTzP1nxYRvCnUum9fliU1WH5gkPrEJyDkIK2X5Ofpts6lA1_0zyyLk12su5oecOUx_Nnvab42l_tTOgCkvT2_hBclyLobDvBKBGoUoTMdAZ3cqT-4C7BbwmzsaxNaGaElc_vWZSq5MEwVpP_3IG06QLYjejRX4s8u4NFwCFm2e5XhISgUrVQsbNrCVlUloqXs3Pl6sY3xUrvOu6jmwl3PN-rEMbbS8jID4Hoao9fGwb62CDhPw'**

**Comment by shoreviewanalytics** [comment]
I believe I was able to fix the issue by adjusting the staticman.yml file.  Here's a link to my staticman.yml file.  

https://github.com/shoreviewanalytics/shoreviewanalytics.github.io/blob/master/staticman.yml

What I did is adjust the format and location of the reCaptcha lines so that they are not under the comments hierarchy.  I also used the exact format taken from _config.yml and no longer get the 500 error.  Feel free to close this one.  Yay!

**Comment by VincentTam** [comment]
@shoreviewanalytics It might be quite late, but just a little suggestion.  It's better to use a permalink which includes the Git commit hash, so that future readers aren't chasing a moving target.

**Comment by umermansoor** [comment]
> I believe I was able to fix the issue by adjusting the staticman.yml file. Here's a link to my staticman.yml file.
> 
> https://github.com/shoreviewanalytics/shoreviewanalytics.github.io/blob/master/staticman.yml
> 
> What I did is adjust the format and location of the reCaptcha lines so that they are not under the comments hierarchy. I also used the exact format taken from _config.yml and no longer get the 500 error. Feel free to close this one. Yay!

I think this just disables the recaptcha. You can try with manual curl and verify that bad tokens also work
