### ISSUE TITLE
Is API call rate limit for all users ?

### ISSUE THREAD

**Issue by gourav** [eduardoboucas/staticman#242]
GitHub API call limit is restricted to 5k/hour. Is this limit for all users ? I mean for everyone using the public staticman API instance ? 

With [this](https://github.com/eduardoboucas/staticman/blob/master/lib/GitHub.js#L138:L166), for a single pull request, app will consume at least 4 Github API call quota for a single comment process request ? 

If that is the case, the maximum amount of comment requests that public instance of StaticMan can serve is restricted around ~1k/hr, which means other than first 1k comment requests, all other comment requests are ignored by GitHub ?

Is that the case ?

**Comment by robinmetral** [comment]
It is. Currently the public instance of Staticman is not scalable.

Some solutions include using Gitlab, or self-hosting your Staticman instance (see #222, #227). Or maybe we could make the public instance scalable by making it a Github app (#243)

**Comment by gourav** [comment]
#243, 
In process.

**Comment by eduardoboucas** [comment]
Closing in favour of #243. Thanks!
