### ISSUE TITLE
Support any git repository server

### ISSUE THREAD

**Issue by mildred** [eduardoboucas/staticman#245]
If moderation is disabled, Staticman should be able to support any kind of git repository just by having a ssh private key and the repository address. Just clone the repository, make a commit and push. It would be great to allow that so it doesn't depends on GitHub any more.

**Comment by VincentTam** [comment]
I like the idea of distangling Staticman from GitHub.  However, an SSH key would give too much power (e.g. write to protected branch/rebase commit history) in case of most Git service providers.  The current model of authentication via OAuth Tokens addresses this problem by limiting the holder's authorities to specific necessary operations (create PR & issues).

**Comment by alexwaibel** [comment]
I too like this idea but think it's infeasible to implement securely so I'm going to mark this wont fix. If anyone has ideas for how to go about this in a secure way, then we can reopen.
