### ISSUE TITLE
Staticman is dead

### ISSUE THREAD

**Issue by donaldboulton** [eduardoboucas/staticman#260]
Have not been able to get staticman to work since November 2018 nor the popcorn repo example, My site and the popcorn example says to many requests and most of the time there is an error with your submission. Move it to netlify, its free and no limits.
If its not going to work anymore then tell everyone so we do not waste our time.
Tried everything api v1 and api v2, it never works.

**Comment by dancwilliams** [comment]
@donaldboulton 

Have you looked at #243 ?

**Comment by VincentTam** [comment]
@donaldboulton I've notified you the power of Staticman v3 through [a comment](https://github.com/donaldboulton/DWB/pull/40) on your post [*Staticman with GitLab*](https://donboulton.com/2018-02-26-post-staticman-with-gitlab).

**Comment by donaldboulton** [comment]
Everything in my site correct and I get this error with api v3,
`{"success":false,"rawError":{"name":"HttpError","status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type","connection":"close","content-encoding":"gzip","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Thu, 17 Jan 2019 16:16:34 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"GitHub.com","status":"404 Not Found","strict-transport-security":"max-age=31536000; includeSubdomains; preload","transfer-encoding":"chunked","x-content-type-options":"nosniff","x-frame-options":"deny","x-github-media-type":"github.machine-man-preview; format=json","x-github-request-id":"D6C2:66C1:4C3E69:B9A514:5C40AA62","x-xss-protection":"1; mode=block"},"request":{"method":"GET","url":"https://api.github.com/repos/donaldboulton/DWB/installation","headers":{"accept":"application/vnd.github.machine-man-preview+json","user-agent":"Staticman agent octokit.js/16.8.0 Node.js/11.6.0 (Linux 4.4; x64)","authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NDc3NDE3OTQsImV4cCI6MTU0Nzc0MTg1NCwiaXNzIjoiMjM1MTUifQ.fIAphVZod1Pj1REdXFo_tTVGp7tD9gq5BU4G0sjvUou5zHEh9F4AybDFVwr8VR1fO-jyFINuAQ2gghCUEDF6v5e3yRl2MICAWLxrB59UEyZsmgd1AwG9q9swgAFkLSVawbE4lMY9RCzvTKI87188226VXw0s3p8h5w8D_-JnCcZWbSrbFkoFUVnyQb8YaaqnvhSCqB5PuqdS7sxA123kdZPFeojIoV6gZpN-xvCYbnnxI_L1_nwsghmaBTZyulET1E1EB3VEn5oekYTr3xjtSktrBc0ars94G2RVqkiMP--kOn1cdqlfgtex61mSCil5E1Mn6Ump7aq7W7islTBK4A"},"request":{"timeout":5000,"validate":{"owner":{"required":true,"type":"string"},"repo":{"required":true,"type":"string"}}}},"documentation_url":"https://developer.github.com/v3/apps/#find-repository-installation","_smErrorCode":"GITHUB_READING_FILE"},"errorCode":"GITHUB_READING_FILE"}`

When I moved to Netlify I started having weird issues like the above, no clue whats up, My email, gpg keys, hooks and tokens are correct. Got Me???

**Comment by VincentTam** [comment]
@donaldboulton Please format your raw JSON error so that it's more readable, and describe what you've done to get this error, so that we can reproduce it.

It seems that you've [forked](https://framagit.org/donaldboulton/staticman) [my fork on Framagit](https://framagit.org/staticman-gitlab-pages/staticman), and you're running your own local `Node.js` instance. From the message `origin-when-cross-origin`, it seems to be a CORS error, which is common in modern browsers.  The proper way to locally test Staticman is to use an HTTP client like Postman.  From the `errorCode`, it seems that your API path is incorrect.  Anyways, that's just my guess.

**Comment by donaldboulton** [comment]
Using netlify functions now issue is a mute point CLOSING

**Comment by pacollins** [comment]
@donaldboulton Do you have a link to your repo where you have switched to netlify functions?

**Comment by VincentTam** [comment]
> @donaldboulton Do you have a link to your repo where you have switched to netlify functions?

@pacollins From the tone of his previous comments, it seems that your questions has to be answered by somebody else.  Perhaps you're referring to the repo for his web site: https://github.com/donaldboulton/DWB/.  If you type "netlify" in the search box, you'll see an array of merged PR's "automatically generated by Netlify CMS".

**Comment by donaldboulton** [comment]
Tested staticman again. with v3  and the install app on github, it worked great for about 10 days and like always in the past 6 yrs Staticman is Still Dead again.
`
Access to XMLHttpRequest at 'https://api.staticman.net/v3/entry/github/donaldboulton/publiuslogic/master/ratings' from origin 'https://publiuslogic.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.staticman.net/v3/entry/github/donaldboulton/publiuslogic/master/ratings:1 Failed to load resource: net::ERR_FAILED`

Its the same on many other sites like [Gatsby Central](https://www.gatsbycentral.com/gatsby-v2-refactoring-cheat-sheet)

On Gatsby Central you get the same response error as my publiuslogic.com site on ratings, and a Heroku error on comments as:

Application error on
https://api.staticman.net/v2/entry/GatsbyCentral/gatsbycentral.com/master/comments

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail.

Whay is this working then broken whats up.

**Comment by VincentTam** [comment]
> Whay is this working then broken whats up.

That's reported in #307.
