### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [eduardoboucas/staticman#265]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by egecelikci** [comment]
Yes, even recently released v3 of API, take a look at [#243](https://github.com/eduardoboucas/staticman/issues/243)

**Comment by DanielRuf** [comment]
Could be probably better to make the dev branch the default one. Besides this it seems the truck factor is (almost) one. An org account could be better imo.

**Comment by alexwaibel** [comment]
Hi Daniel, I've recently picked up this repo so it is indeed actively maintained. For more information about the current project status, see #317 and #318
