### ISSUE TITLE
Cann't hook up my forms

### ISSUE THREAD

**Issue by geekbanana** [eduardoboucas/staticman#27]
Follow the document at https://staticman.net/docs/index.html.

**Step 1. Add Staticman to your repository**    SUCCEED.
![image](https://cloud.githubusercontent.com/assets/11587781/18228754/7cbebcf6-728e-11e6-82ac-04b37fc86690.png)

**Step 2. Add Staticman to your Jekyll config file**,  here is my _config.yml https://github.com/gncavalry/gncavalry.github.io/blob/master/_config.yml

Then I tried to submit a comment at page https://gncavalry.github.io/test/ , but failed.
According to the browser consol , it says :"Failed to load resource: the server responded with a status of 500 ()"

![image](https://cloud.githubusercontent.com/assets/11587781/18228697/2fbe19ee-728c-11e6-8b7c-3aadd7e1d718.png)

Then, I use PostMan to do this step and got returned errorCode :"MISSING_PARAMS". (But I have post all three require fileds .)
![image](https://cloud.githubusercontent.com/assets/11587781/18228709/a5fbc246-728c-11e6-919c-413d44547879.png)

My project is fork form **mmistakes/minimal-mistakes** , here is my comments.hmtl: https://github.com/gncavalry/gncavalry.github.io/blob/master/_includes/comments.html 
I have never changed it , and It's filelds name is correct 
![image](https://cloud.githubusercontent.com/assets/11587781/18228742/37adafc8-728e-11e6-902a-7b74759d951d.png)

I'm dicussing this question with **Michael Rose** at this issue https://github.com/mmistakes/minimal-mistakes/issues/503 , but have no answer.

So, could you help me to figure it out ? Thank you very much.

This is my test page: https://gncavalry.github.io/test/

**Comment by mdxprograms** [comment]
@gncavalry I'm having the same issue. I'm also having an issue with `path` when getting a `422` response code.

**Comment by geekbanana** [comment]
@mdxprograms  my response code is 500. I have change my github username twice , I don't know if it has affect.  Have you ever changed your github username ?

**Comment by mdxprograms** [comment]
@gncavalry I haven't but now that I think about it I've deleted my master branch and recreated it, but I'm also trying to use a different branch than master. I've changed my config to match and still no success.

**Comment by eduardoboucas** [comment]
@gncavalry It appears your error is being caused by a duplicate key in your `_config.yml` file. After a quick glance, it seems that you're declaring `defaults` twice. Can you try correcting this and see if you still experience the same issue?

@mdxprograms Can you provide a link to the page you're using to submit the form?

**Comment by geekbanana** [comment]
Thank you very much , I commented both <code>defaults</code>  and <code>include: ["_pages"]</code> in line 248 , 247 . Then comment works ! Thank you ~

**Comment by eduardoboucas** [comment]
Great! In that case I'll close this issue.

@mdxprograms your issue seems to be different, so if you're still experiencing difficulties, please open a new one, supplying as much info as possible so I can help debug.

**Comment by mdxprograms** [comment]
Thanks @eduardoboucas I'm out of town for the weekend but I'll give it another go and open an issue if it persists.

**Comment by stregerdev** [comment]
I am experiencing the same 500 error as gncavalry except I do not have the duplicate default settings. My config file is located at https://github.com/stregerdev/stregerdev.github.io/blob/master/_config.yml. I'm not quite sure what is causing the error.
