### ISSUE TITLE
Instructions to use the Github app

### ISSUE THREAD

**Issue by kuworking** [eduardoboucas/staticman#271]
I have posted a **StackOverflow** question&answer describing what has worked for me to get `staticman` up and running

https://stackoverflow.com/questions/54898580/how-to-use-staticman-with-react-gatsby/54898581#54898581

I guess the _staticman api url_ will change when the app goes official? I haven't been able to find any doc describing this, so until it is updated, maybe this helps somebody like myself one day ago :)

*and, if there's any mistake, please correct it

**Comment by sukiletxe** [comment]
See https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860 for details.

**Comment by alexwaibel** [comment]
Duplicate of #312
