### ISSUE TITLE
Cannot get staticman to display. 

### ISSUE THREAD

**Issue by valzi** [eduardoboucas/staticman#276]
I have no errors, but nothing displays in my posts. (See here: https://light-transmuter.netlify.com/posts/4weeks3/). I'm using v3 of the post method.

Would you give me suggestions? I feel as if I've read and done everything, but I suspect I am missing something simple. I'm new to Hugo.

Here is the relevant code:
https://github.com/valzi/light-transmuter/blob/master/config.toml
https://github.com/valzi/light-transmuter/blob/master/staticman.yml
https://github.com/valzi/light-transmuter/blob/master/layouts/partials/staticman-comments.html
https://github.com/valzi/light-transmuter/blob/master/layouts/_default/single.html

Here's a [sample post](https://light-transmuter.netlify.com/posts/4weeks/).

**Comment by valzi** [comment]
I have no idea why, but the forms are now showing up. However, submitting a comment generates this error without moving to a new url. 
![image](https://user-images.githubusercontent.com/4284600/54497520-411fc580-48c1-11e9-9949-b25759d1a3e3.png)

**Comment by valzi** [comment]
Hey, please let me know if it's rude to bump. Just wanted to check in to say that I've failed to make any progress on my own.

**Comment by valzi** [comment]
Hey, please let me know if it's rude to bump. Just wanted to check in to say that I've failed to make any progress on my own.

And I've been trying with the example code from the staticman getting started page instead of the partial I linked above. When I do that, I get 

`Rebuild failed: "C:\Users\valzi\Dropbox\GitHub\light-transmuter\layouts\_default\single.html:19:1": parse failed: template: _default\single.html:19: function "page" not defined`

Here is the code for the single.html that causes that:

``` {{- define "main" }}
<div>
  <div>
    <h2 class="post-title">
      {{ if .Draft }}DRAFT: {{ end }}
      {{ .Title }}
    </h2>
    {{ partial "post_meta.html" . }}
  </div>
  <div>
    {{ .Content }}
  </div>
  <hr>
  <div>
    Comments
    <form method="POST" action="https://api.staticman.net/v3/entry/github/valzi/light-transmuter/master/comments">
  <input name="options[redirect]" type="hidden" value="https://my-site.com">
  <!-- e.g. "2016-01-02-this-is-a-post" -->
  <input name="options[slug]" type="hidden" value="{{ page.slug }}">
  <label><input name="fields[name]" type="text">Name</label>
  <label><input name="fields[email]" type="email">E-mail</label>
  <label><textarea name="fields[message]"></textarea>Message</label>

  <button type="submit">Go!</button>
</form>
<!--    {{ partial "related.html" . }}
    {{ partial "staticman-comments.html" . }}-->

<!--    {{ partial "staticman/form-comments" . }}
    {{ partial "staticman/show-comments" . }} -->
<!--    {{ template "_internal/disqus.html" . }} -->
  </div>
</div>
{{- end }} ```

**Comment by valzi** [comment]
Bump

**Comment by onwingslikeeagles** [comment]
Hello,

In an attempt to gather more information about your project, I decided to perform a _curl_ function on it. The results are seen here: ```curl -d "fields[email]=foobar@gmail.com" -X POST https://api.staticman.net/v3/entry/github/valzi/light-transmuter/master/comment
{"success":false,"rawError":{"_smErrorCode":"MISSING_CONFIG_BLOCK"},"errorCode":"MISSING_CONFIG_BLOCK"}```

As you can see, the error code _MISSING_CONFIG_BLOCK_ appeared. Referenced in issue #106, this individual received the same error and stated that it had something to do with his configuration file (i.e. staticman.yml). I see in your file you have several attributes toward the bottom that may (or may not) be in the correct format. I would copy over the sample yml file as in the GitHub code and test with those parameters to ensure the project works, then update each additional attribute line by line, as needed.

Hope this helps.
