### ISSUE TITLE
Cors Proxy Issue

### ISSUE THREAD

**Issue by onwingslikeeagles** [eduardoboucas/staticman#278]
Hello. I've worked with various commentators about this project on issue #243. I've seen great success from moving to from to a GitHub specific application. I'm sharing this information beforehand to state that I've seen the project in a working state before.

With that being said, my project is currently experiencing a cors proxy issue. Below is the following error I'm receiving:

`Access to XMLHttpRequest at 'https://dev.staticman.net/v3/entry/github/discordUser/discordRepo/discordBranch/staticmanId' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Note:** Information beginning with _discord_ and _staticman_ have been replaced by default names because it's a private repository. 

This behavior has started happening since yesterday. Are there any known issues with the application as of then? Is anyone else able to replicate this issue with the current application v3?

**Comment by onwingslikeeagles** [comment]
**Update:** Another developer on our team mentioned that it's not a cors issue after all. Cors was turned off on their browser and they received an error code of 503. This to me infers that there's an issue with the system itself. The issue still exist as of writing this comment.

**Comment by bernikr** [comment]
I get the same error on my personal blog, and when trying to post a comment with Postman I get a generic [herokucdn application error](https://www.herokucdn.com/error-pages/application-error.html). I think there is something wrong with the hosted staticman instance.

**Comment by casually-creative** [comment]
Confirming that the problem is indeed still happening and is a major blocking issue. As of now our team can not continue using this hosted version of staticman. Sorry for the ping @eduardoboucas but this to me seems like an urgent matter.

**Comment by eduardoboucas** [comment]
The development API (`dev.staticman.net`) is running on a free tier Heroku instance. Because too many people started using it in their projects, it reached its limits.

I have merged the v3 endpoints into the production API (`api.staticman.net`), which should now have the exact same capabilities as the development one. If you use this one instead, you should no longer see these errors.

Please reopen this issue if the problem still occurs.

Thanks!

**Comment by casually-creative** [comment]
Thank you very much! Seems like we forgot we were working on the dev instance. Swapping to the production API fixed the issue!

**Comment by hatamiarash7** [comment]
I have this issue with `api.staticman.net` :(
