### ISSUE TITLE
"Too many requests" error (Part 2)

### ISSUE THREAD

**Issue by onwingslikeeagles** [eduardoboucas/staticman#279]
Hello,

Allow me to give some background before I begin discussing this issue. A while ago, an issue (#222) was created that dealt with an error that was received from the Staticman tool referred to as _too many requests_. After researching this issue, it seems that having a public instance of the tool was causing it to reach GitHub's API limitation, since everyone was using the same API key. To resolve this, Eduardo created a GitHub application that everyone connected to their own repositories instead of using the public instance and assigning a collaborator. This is referenced in #243. 

After implementing this project, with the addition of updating it to the production URL (as referenced in #278), our team is again experiencing the _too many requests_ issue. Seeing as how we never experienced this during the development version, it may still stem from a similar API key, but further research will need to be performed. I'm creating this issue to begin the conversation to solve this.

**Comment by onwingslikeeagles** [comment]
It has been a while since I've revisited this issue, but my team is beginning to experience it again. I see several others have acknowledged that they are seeing this issue with the latest version of the application as well. 

Pinging @eduardoboucas for further inspection, as I believe this will need to be another restructure and simply not an update to the application.

**Comment by RossComputerGuy** [comment]
Yeah, I'm getting this issue. I'm thinking that I'll have to drop the comment support on my site for now.

**Comment by onwingslikeeagles** [comment]
It has been a month since my last post on this thread and I haven't found a solution. I believe this will entail more details about the GitHub application itself and not the client side, as additional people have marked this issue as being seen since then. Pinging @eduardoboucas again to begin research on this issue.

**Comment by VincentTam** [comment]
Even though I haven't (and won't) use the new GitHub Apps method, but I suspect that spam comments have contributed to most of the comments, and thus they are the culprit for the GitHub App's API limit.  Note that spam comments were reported in eduardoboucas/staticman#175 long ago.

**Comment by alexwaibel** [comment]
Once this repo is restored to working order I suspect the best way to handle this will be hosting your own private instance.

**Comment by alexwaibel** [comment]
Duplicate of #317

**Comment by RossComputerGuy** [comment]
@alexwaibel Why is this one marked as duplicate of #317? Isn't the other issue newer than this one?

**Comment by alexwaibel** [comment]
You're correct that technically #317 is the duplicate. However, given the the repo was not maintained actively for a period of time I need to clean up the issues. I find it preferable in this case to make an issue which details the state of the project and then point all related issues to that one. This way all the relevant discussion is linked in one place and is easily visible as the latest issue.
