### ISSUE TITLE
Is there any way to embed staticman comment system in non-jekyll websites?

### ISSUE THREAD

**Issue by karunakarpatel-kp** [eduardoboucas/staticman#295]
Hi, 
I hosted my website hosted on Github as Github pages without using any static site generators (example: Jekyll). 
I created my own HTML webpage with my own design and code which I have hosted my webpage as Github pages. 
I was wondering that, Is there any way to integrate or embed Staticman comment system directly in my HTML page as that same HTML page is hosted on Github. 
Thank you, 
[Karunakar Pate Blog](https://www.alltechnotricks.com).

**Comment by idgman** [comment]
Yes, you can add the staticman.yml file to the base of the repository and add the comments form to the blog pages as you would on a Jekyll website, just without the shortcodes.

**Comment by VincentTam** [comment]
To respond to the question in the title, here's [a list of (mainly Hugo) Staticman demo sites on Framagit](https://framagit.org/staticman-gitlab-pages) that I've created over fhe past few months.  They prove that Staticman also works well with GitLab Pages.

**Comment by x2v0** [comment]
test

**Comment by x2v0** [comment]
### _**test**_ http://protom.ru
