### ISSUE TITLE
"Application error" when trying to connect a new repository

### ISSUE THREAD

**Issue by nverinaud** [eduardoboucas/staticman#296]
I try to connect Staticman to my repository (Step 1 of "Getting Started") but it fails with an error from Heroku.

Here is the URL I call : `https://api.staticman.net/v2/connect/Ryfacto/academie.ryfacto.fr`.

And the response :

```html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <title>Application Error</title>
        <style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
    </head>
    <body>
        <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
    </body>
</html>
```

Thanks a lot for your help !

**Comment by deadlydog** [comment]
I'm also having this same issue.

![image](https://user-images.githubusercontent.com/1187140/59486534-cd954200-8e36-11e9-9a74-9e98ac46515d.png)

![image](https://user-images.githubusercontent.com/1187140/59486569-eaca1080-8e36-11e9-8b12-ef6bdbcf7133.png)

I'm not sure if it's related, but I noticed that [the build is also failing](https://travis-ci.org/eduardoboucas/staticman). Perhaps a bad version got pushed out?

**Comment by deadlydog** [comment]
I found issue #243 and installed the app instead of going the contributor route. I think this (using v3) is the new recommended practice, but the docs have not been updated yet.

**Comment by huobi-registraciya** [comment]
I'm also having this same issue!

**Comment by askurashev** [comment]
I'm too.

**Comment by ayaxxchanz** [comment]
Hi. Any fix to this problem? I try to install Staticman with my Hugo site but always got this same error. The documentation is outdated. I also came across with several websites to ask questions about this but every time I want to post a comment, I receive this application error too (including the demo site https://hugo.staticman.net/ )

**Comment by tomasparks** [comment]
me too

**Comment by VincentTam** [comment]
@ayaxxchanz The official Hugo + Staticman demo site is using the official developement API instance v2.  Perhaps commit d8007868e1571c191f862315e598e96741e7867f breaks support for v2, despite the project owner's intention to remain support for v1 & v2 (see below).

Edited: for a fix, you might consider #285.

@tomasparks Please avoid duplicating issues to keep discussion focused.

> I found issue #243 and installed the app instead of going the contributor route. I think this (using v3) is the new *recommended* practice, but the docs have not been updated yet.

@deadlydog That's against what the project owner's idea in https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453876235, so I don't think that's *recommended* by collaborators who don't wish to break current support and interupt the service, in light of [**@staticmanapp**'s huge "contributions" on GitHub](https://github.com/search?q=author%3Astaticmanapp&type=Issues).

**Comment by zxdawn2** [comment]
@VincentTam I can't find `staticmanapp` on GitHub:
![image](https://user-images.githubusercontent.com/50947063/60877607-bea48280-a270-11e9-8d95-52c0e5be2a54.png)

**Comment by VincentTam** [comment]
@zxdawn2 I don't own the official instance, so nobody can fix this except the author.  You may try using an alternative instance (i.e. anything that's NOT official), like @staticmanlab, @staticmanaima, @BloggerBust-bot, etc.

P.S. I maintain the first one, and I helped the setup of the 2nd one through GitHub issues.  I've only tested mine.  If you want to use mine, please refer to the later half of https://github.com/einsteinpy/blog.einsteinpy.org/issues/12#issue-449871630 and adapt it to your repo.  I'm too lazy to retype everything again.  Please don't hesitate to ping me in case of questions.

**Comment by zxdawn2** [comment]
@VincentTam I tried to visit `https://staticman3.herokuapp.com/v3/connect/github/zxdawn2/zxdawn2.github.io/master/comments`, but I get this error:
```
Cannot GET /v3/connect/github/zxdawn2/zxdawn2.github.io/master/comments
```

BTW,  I use this method to add comments:
```
<form method="POST" action="https://staticman3.herokuapp.com/v3/connect/github/{{ .Site.Params.staticman.username }}/{{ .Site.Params.staticman.repository }}/{{ .Site.Params.staticman.branch }}/comments">
```

As a result, when I try to post, I got this error:
```
Cannot POST /v3/connect/github/zxdawn2/zxdawn2.github.io/master/comments
```

**Comment by VincentTam** [comment]
@zxdawn2 Thanks for your invitation to @staticmanlab.

1. The link for accepting the invitation is  
https://staticman3.herokuapp.com/v3/connect/github/zxdawn2/zxdawn2.github.io/  
Explanation: You invite a GitHub/GitLab user to the *whole* repo, not just to a particular branch.
2. To hook up your HTML form with Staticman API. you need `/entry` instead of `/connect`.

       <form method="POST" action="https://staticman3.herokuapp.com/v3/entry/github/{{ .Site.Params.staticman.username }}/{{ .Site.Params.staticman.repository }}/{{ .Site.Params.staticman.branch }}/comments">

    Note that `comments` is just a property name in `staticman.yml`.  You may change it to any name you like.  For example, https://github.com/okfde/offenerhaushalt.de/blob/gh-pages/staticman.yml.

**Comment by zxdawn2** [comment]
@VincentTam thanks!
Although comment works, subscribe button doesn't work:
https://github.com/zxdawn2/zxdawn2.github.io/blob/3a9b470ddd13ac1c8bb2831d1e15d30d55505ef2/themes/AllinOne/layouts/partials/staticman/form-comments.html#L30-L37
Is that caused by @staticmanlab?

**Comment by VincentTam** [comment]
> @VincentTam thanks!
> Although comment works, subscribe button doesn't work:
> https://github.com/zxdawn2/zxdawn2.github.io/blob/3a9b470ddd13ac1c8bb2831d1e15d30d55505ef2/themes/AllinOne/layouts/partials/staticman/form-comments.html#L30-L37
> Is that caused by @staticmanlab?

@staticmanlab _doesn't_ touch Akismet and Mailgun because his main goal is to show that Staticman's GitLab integration works, so that a truly open-source staticman commenting system is, in principle, feasible, for static sites hosted on Framagit, which is open-source.

Before the appearance of a free (as in both free beer and in freedom) alternative of Akismet and/or Mailgun, @staticmanlab won't try them.

**Comment by zxdawn2** [comment]
Thanks! However, mailgun has free account option. Why not support it?On Aug 3, 2019 14:00, Vincent Tam <notifications@github.com> wrote:
@VincentTam thanks!
Although comment works, subscribe button doesn't work:
https://github.com/zxdawn2/zxdawn2.github.io/blob/3a9b470ddd13ac1c8bb2831d1e15d30d55505ef2/themes/AllinOne/layouts/partials/staticman/form-comments.html#L30-L37
Is that caused by @staticmanlab?

@staticmanlab doesn't touch Akismet and Mailgun because his main goal is to show that Staticman's GitLab integration works, so that a truly open-source staticman commenting system is, in principle, feasible, for static sites hosted on Framagit, which is open-source.
Before the appearance of a free (as in both free beer and in freedom) alternative of Akismet and/or Mailgun, @staticmanlab won't try them.

**Comment by VincentTam** [comment]
> However, mailgun has free account option. Why not support it?

1. In this case, "free" as in "free beer" is offered, but not "free" as in "freedom" in GNU's norms.
2. @staticmanlab's main goal is to test and demonstrate Staticman's native GitLab support, which had not yet been merged against the `master` branch, so I tried my best to minimise the [setup](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/) and the corresponding [git diff between the `dev` branch at `55d14306` and my `deploy` branch](https://github.com/eduardoboucas/staticman/compare/55d14306d851059a2a27d24b5eb4cb17c5009477..VincentTam:deploy).

**Comment by zxdawn2** [comment]
@VincentTam Thank you for your help! I rebuilded the [repository](https://github.com/zxdawn2/zxdawn2.github.io) and got another problem:
The Comment content at the end of this [page](https://zxdawn2.github.io/2019/08/17/hugo-staticman-travis/#/reference) looks different from local (hugo server).

Local: 
![image](https://user-images.githubusercontent.com/50947063/63211626-63499800-c12c-11e9-9e0c-a4c8d620fdca.png)

WEB:
![image](https://user-images.githubusercontent.com/50947063/63211629-70ff1d80-c12c-11e9-8c30-9716c7af9fbd.png)

**Comment by VincentTam** [comment]
> @VincentTam Thank you for your help! I rebuilded the [repository](https://github.com/zxdawn2/zxdawn2.github.io) and got another problem:
> The Comment content at the end of this [page](https://zxdawn2.github.io/2019/08/17/hugo-staticman-travis/#/reference) looks different from local (hugo server).
> 
> Local:
> ![image](https://user-images.githubusercontent.com/50947063/63211626-63499800-c12c-11e9-9e0c-a4c8d620fdca.png)
> 
> WEB:
> ![image](https://user-images.githubusercontent.com/50947063/63211629-70ff1d80-c12c-11e9-8c30-9716c7af9fbd.png)

@zxdawn2

1. The project is about the Node.JS app that converts HTML form data into GitHub/GitLab pull/merge requests.  It *shouldn't* care whether you use GitHub/GitLab pages or not, as @<span></span>eduardoboucas commented in https://github.com/eduardoboucas/staticman/issues/278#issuecomment-475170669.  Your project is about the display of a HTML form, which has *nothing* to do with the structure of the form data, so perhaps you have to find a better place to ask, like [Hugo Discourse](https://discourse.gohugo.io/).
2. To ensure that your Staticman config is correct, a quick way to test is to use API clients like [Postman](https://www.getpostman.com/), as @<span></span>ntsim suggested in #219.
3. Please be aware of the "503 Service Unavailable" error of the official production instance "api.staticman.net" in issue #307.

**Comment by ajbozdar** [comment]
Is staticman dead? When I try to add it as a collaborator, it says no such user exists.

**Comment by VincentTam** [comment]
> Is staticman dead? When I try to add it as a collaborator, it says no such user exists.

@ajbozdar Your question has already been asked in #306.

**Comment by alexwaibel** [comment]
Duplicate of #317
