### ISSUE TITLE
Add Deploy to Heroku Button

### ISSUE THREAD

**Issue by infominer33** [eduardoboucas/staticman#305]
https://devcenter.heroku.com/articles/heroku-button
>The ‘Deploy to Heroku’ button enables users to deploy apps to Heroku without leaving the web browser, and with little or no configuration. The button is ideal for customers, open-source project maintainers or add-on providers who wish to provide their customers with a quick and easy way to deploy and configure a Heroku app.

A deploy to Heroku would ease the rush of users overloading your app because they don't know how to easily run their own.

I might add that I eventually figured out how to run my own instance with this gist...  finding a fork that will work for me was another story. I did have help from [@staticmanlab](https://github.com/staticmanlab), tho I can't remember if it was the difference in the code or if it was just some setting they pointed out to me.. or maybe both..

https://gist.github.com/ujjwal96/70eabafefa8c2e3f5fa900f352f16c5e

**Comment by alexwaibel** [comment]
I just wrote up some instructions in the README as part of #319, but I like this idea a lot more. I'll definitely look into adding this. Thank you for the suggestion.

Edit: Addressed in #319

**Comment by alexwaibel** [comment]
#319 has been merged into master so this has now been fully resolved.

**Comment by infominer33** [comment]
woo hoo!
