### ISSUE TITLE
Akismet not working

### ISSUE THREAD

**Issue by zongren** [eduardoboucas/staticman#31]
I have added akismet configuration to the [_config.yml](https://github.com/zongren/comment/blob/master/_config.yml) file,but it seems not to work.`TOTAL API CALLS` is always zero.

**Comment by zongren** [comment]
sorry:smile:,my bad,didn't read the document carefully

**Comment by infominer33** [comment]
just want to note that after adding akismet variables to the config.production.json

```
"AKISMET_SITE": "https://website.com"
"AKISMET_API_KEY": "akismetapikey"
```

I had to set an environment varable to tell node to use the production config

I added this line to /etc/environment
```
NODE_ENV=production
```
