### ISSUE TITLE
Does this project still work?

### ISSUE THREAD

**Issue by alexwaibel** [eduardoboucas/staticman#315]
I'm rather perplexed as I've tried all manner of things to attempt to get this project running and just haven't been able to. This is confusing to me as it seems like a decent number of blogs rely on this project to operate but the documentation for this entire project is outdated and wrong in many places.

### My environment
I'm trying to connect my personal website:
* Username: alexwaibel
* Repo name: alexwaibel.github.io
* Heroku mirror of Staticman: https://staticman-alex-waibel-mirror.herokuapp.com/
    * Instance variables which I've set:
        * GITHUB_TOKEN
        * RSA_PRIVATE_KEY

### What I've tried so far
*  I've attempted to call a `GET https://staticman-alex-waibel-mirror.herokuapp.com/v2/connect/alexwaibel/alexwaibel.github.io`
    * This gets me a `HTTP 500` which I think is indicative of a problem with the current master branch. I get the following error if I run the server in debug mode:
![image](https://user-images.githubusercontent.com/7026879/68109790-540ef680-fea0-11e9-9980-b22753d323b6.png)
* I've attempted to call a `GET https://api.staticman.net//v2/connect/alexwaibel/alexwaibel.github.io`
    * This is met with `HTTP 503`

### Some digging
It seems maybe this problem comes from the connect controller not passing an API version to the Github helper. I'd try changing this myself to test it but I can't even get the server to start :(

It seems someone may have [broken the latest build](https://travis-ci.org/eduardoboucas/staticman). This repo seems to be kind of a mess. Is there a maintainer still? If so, are you accepting contributors? This is a dependency for my website and I've got some free time lately.

**Comment by ruddra** [comment]
Probably you can look at this PR https://github.com/eduardoboucas/staticman/pull/314(specially this file: https://github.com/eduardoboucas/staticman/blob/d615599118e281d2170a0aa1a1ea43cd8fee8f3b/lib/GitHub.js). I put an hack to fix it. FYI I haven't had the time to fix the tests yet that why travis CLI is failing.

**Comment by fbnlsr** [comment]
I don't know if @eduardoboucas still maintains the project tbh. I was stuck for months until I switched to @staticmanlab. I'm in the process of searching for a new service to handle comments as it's unfortunately not reliable enough, despite the fast that it's really an elegant solution.

**Comment by alexwaibel** [comment]
Well... Hopefully @eduardoboucas shows up some time soon. If not I may be able to muster up the time in the near-ish future to  take over and clean it up a bit.

**Comment by fbnlsr** [comment]
What could be really nice is a proper tutorial on how to deploy your own Staticman instance.

Staticman still works perfectly, but it's plagued by the fact that people are using the free service provided by Eduardo, and it hits Github's limitations. The real way to use it should be for people to deploy their own private instance on Heroku or somewhere else, don't you think?

**Comment by alexwaibel** [comment]
While I completely agree, have you actually been able to use static man recently? I had to tinker with it to even get it to `npm start`. If so, I'd love to hear more about your setup.  @fbnlsr

**Comment by alexwaibel** [comment]
@VincentTam I see you've done a lot of work on this repo in the past. Do you know of a working commit of this project?

**Comment by fbnlsr** [comment]
> While I completely agree, have you actually been able to use static man recently? I had to tinker with it to even get it to `npm start`. If so, I'd love to hear more about your setup. @fbnlsr

I haven't deployed my own instance I must admit. I've switched to using @staticmanlab (Vincent's bot) as an emergency backup and plan on deploying my own instance of Staticman (or at least try to) as soon as I have some free time.

**Comment by alexwaibel** [comment]
I do completely agree that providing users with the instructions to deploy their own instances is for the best. I plan to update add such instructions once I can get my own instance functional again

**Comment by alexwaibel** [comment]
To answer my own question, this project in the current state of the master branch does not work. The express server does not start and many tests are failing. I've been granted contributor rights and will be working on restoring this repo to working order.

**Comment by VincentTam** [comment]
@alexwaibel Sorry for late reply.  The only thing that I remembered now is PR #<span></span>219.
