### ISSUE TITLE
Unable to add staticmanapp as collaborator. 

### ISSUE THREAD

**Issue by marvindanig** [eduardoboucas/staticman#323]
Reference: the following [tweet](https://twitter.com/marvindanig/status/1207069174062813184).

**Comment by KirinFuji** [comment]
Same issue. 

User is gone link results in 404.

https://github.com/staticmanapp/

**Comment by marvindanig** [comment]
I think it was the spammers that did this one in: 

https://github.com/eduardoboucas/staticman/issues/298
