### ISSUE TITLE
Jekyll nested comments sorting

### ISSUE THREAD

**Issue by wini3d** [eduardoboucas/staticman#324]
Not entirely related to staticman, but I was wondering if someone has implemented a reverse order sorting of comments with Jekyll + StaticMan, which is newest on top first.

Perhaps some default sample templates for the front end could be provided for popular static generators like Jekyll.

Thanks.

**Comment by japorized** [comment]
Try looking into the reversed filter that is provided by Liquid.
You may find this [SE question](https://stackoverflow.com/questions/12465521/for-loops-in-liquid-using-reversed-in-conjunction-with-limit1) helpful.

**Comment by willymcallister** [comment]
My Jekyll/Staticman web site sorts comments with the newest at the top.
https://spinningnumbers.org/a/staticman.html
Find a link to my github repository in the footer. 
The file you should look at is _includes/comments.html.

**Comment by alexwaibel** [comment]
Thank you for that example @willymcallister! This appears to be resolved so I'm going to close the issue but feel free to ask any further questions.
