### ISSUE TITLE
Maybe undeclard dependency on 'standard'?

### ISSUE THREAD

**Issue by travisdowns** [eduardoboucas/staticman#337]
When I do a fresh clone of staticman on Ubununtu 19.04 and run `npm test`, I get:

~~~
$ npm test
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> staticman@3.0.0 test /home/tdowns/dev/staticman
> standard && jest

sh: 1: standard: not found
npm ERR! Test failed.  See above for more details.
~~~

Does this mean there is an undeclared dependency on `standard` whatever that is?

**Comment by alexwaibel** [comment]
Standard is what ensures consistent code style across the application. It's listed as a dev dependency in the package.json file so it should be installed. I'll take a deeper look when I have a chance but for now you can try manually installing it with npm

**Comment by travisdowns** [comment]
@alexwaibel - it is possible I had a network error (FWIW npm seems to have poor handling when this occurs, everything appeared to work), I think we can close this.

After a couple more `npm install standard` calls it worked (but not after the first!).
