### ISSUE TITLE
Why are Akismet's site and apiKeys configured in API config file (config.{ENVIRONMENT}.json) but not in site config file (staticman.yml)?

### ISSUE THREAD

**Issue by PhuNH** [eduardoboucas/staticman#339]
Could the author or the maintainer or someone please explain? I don't know if I miss something but Akismet's `site` and `apiKeys` being configured in the API config file means that the site owner must also be the owner of the staticman server. So how did staticman work when the public instance was still supported, and the GitHub user named "staticmanapp" was expected to be added as a collaborator of the site's repository, which means that the site's owner is not necessarily the same as the staticman server's owner?

**Comment by PhuNH** [comment]
I think maybe I have figured it out. It would be nice if someone can confirm.
The Akismet's site should be the URL of the staticman API, not the GH page's. Let's say staticman is hosted on Heroku, then the Akismet's site should be a Heroku URL.
Is it correct?

**Comment by alexwaibel** [comment]
I believe that to be the case, though I should note that I have not yet had time to go through all of the Akismet setup myself. I'm going to go ahead and close this since it looks like you figured it out but feel free to ask any follow-up questions.
