### ISSUE TITLE
Getting really large amount of spam comments

### ISSUE THREAD

**Issue by hajekj** [eduardoboucas/staticman#340]
Hello, I am using staticman (hosted version) on my personal blog. Staticman is configured with reCaptcha from Google, yet I am getting really large amount of spam - https://github.com/hajekj/hajekj.github.io/pulls?q=is%3Apr+is%3Aclosed

The minimal mistakes theme also includes the "honeypot" field and so on, but it appears to have little no effect. Captcha is v2 checkbox set as "Most secure" but still nothing. I like #195 which would allow me to use Akismet with the hosted version. Any ideas what could help me?

**Comment by alexwaibel** [comment]
Sorry to hear you're experiencing large amounts of spam. For the fastest and most reliable solution, I'd definitely recommend switching to hosting your own instance on Heroku. Otherwise I'll still be looking into potentially merging that change but it may be some time as I'm quite busy lately.

**Comment by hajekj** [comment]
I have checked the PR and it seems okay to me, so would be cool if you could sign-off on it.

**Comment by Lusitaniae** [comment]
I removed the action param from the form and only put it together and add it back to the form after page load with JS. 

Seems to have killed most bot comments

**Comment by hajekj** [comment]
I fixed this by running my own instance along with Akismet - https://hajekj.net/2020/04/15/staticman-setup-in-app-service/

Looks like it works real good.

![image](https://user-images.githubusercontent.com/8337913/81278922-a949e180-9056-11ea-9e09-6c58f20308aa.png)

**Comment by codeconomy** [comment]
> I removed the action param from the form and only put it together and add it back to the form after page load with JS.
> 
> Seems to have killed most bot comments

@Lusitaniae
Hi there, would you mind clarifying what you did here? (Trying to find a way to get rid of all the spam)

**Comment by Lusitaniae** [comment]
Something like this

```

window.addEventListener('load', function(){

    var form = document.getElementsByTagName('form');
    base = "{{ .Site.Params.staticman.base }}"
    version = "{{ .Site.Params.staticman.version }}"
    target = "{{ .Site.Params.staticman.target }}"
    if(form.length > 0) {
      form[0].setAttribute('action', base + version + target);
    }

}, false);
```

The params:
```
[params.staticman]
  base = "https://comment.DOMAIN.com/"
  version = "v2"
  target = "/entry/GH-ACCOUNT/GH-REPO/master/comments"
```

**Comment by codeconomy** [comment]
@Lusitaniae Many thanks for reverting quickly, got it now. Just implemented, waiting for the bots now.

**Comment by Lusitaniae** [comment]
Hope it helps, was enough to solve the spam in my website (smallish website)
