### ISSUE TITLE
Request suggested debug methodology for "MISSING_CONFIG_BLOCK" error

### ISSUE THREAD

**Issue by lrdj** [eduardoboucas/staticman#345]
Firstly, can I thank Alex and Eduardo for all the amazing work on Staticman. I can see Alex has spent an amazing amount of time helping people debug their builds, so thank you for that work and also if you have a donation link I'd be happy to buy you a coffee:-)

I've just built Staticman using Travis Down's really thorough guide (and thanks to Travis as well!) at https://travisdowns.github.io/blog/2020/02/05/now-with-comments.html 

I'm now live but have not yet registered for captcha so that's still disabled in the config file.

On comment submission I'm getting an error:

```
success	false
message	"Error whilst parsing Staticman config file"
rawError	
_smErrorCode	"MISSING_CONFIG_BLOCK"
errorCode	"MISSING_CONFIG_BLOCK"
```
Response headers:

<img width="626" alt="response_headers" src="https://user-images.githubusercontent.com/24533243/78425024-987a0a80-7669-11ea-8743-6317de8aeb8a.png">

Can you suggest the best approach to debugging this?

Also, is there any way for the comment system to work with no client-side javascript as this might make debugging a little easier?

Thanks again and all the best:-)
Dug

**Comment by travisdowns** [comment]
The `MISSING_BLOCK` error in principle occurs only when the expected block is missing from the config, but actually (for the code in master) occurs basically any time anything goes wrong when staticman is trying to connect to the target repo, due to flaws in the error handling. E.g., if the connection fails, if the repo doesn't exist, if the credentials/token is rejected, etc.

To get a better error message, you could use the `dev` branch in this repo, as @alexwaibel has [just fixed this issue there](https://github.com/eduardoboucas/staticman/pull/342). You could also use [my fork](https://github.com/travisdowns/staticman), which fixes this issue, although it's behind master by about 19 commits at the moment.

FWIW, I had the same error as you and the problems turned out to be:

1) github revoked my auth token because I checked it into github in a test branch, this makes the auth fail
2) i had a spotty internet connection and so github API was timing out (this only happened when I was testing locally, presumably Heroku itself rarely has a "spotty connection")

You are _almost_ looking in the right place for the error message: you need to look in the actual text of the response, not just the headers. The text will have additional error info (once you've updated your staticman to one of the branches above).

**Comment by travisdowns** [comment]
@alexwaibel - could maybe confirm if his changes are in master, I could be wrong that they are only in dev.

**Comment by alexwaibel** [comment]
@lrdj thank you for your kind words. I maintain this project in my free time so it's always nice to hear positive feedback from users. @travisdowns is correct in his suggestions. The error handler fixes he references are indeed only in the dev branch at the moment, so I'd recommend deploying from that for now. If you switch to viewing the README on the dev branch, the deploy to Heroku button is smart and it'll deploy the dev branch instead.

As far as making requests without JavaScript, you should be able to submit comments using a plain HTML form. See step 3 [on this page](https://staticman.net/docs/) for an example.

You can monitor #346 to see when these fixes are in master.

**Comment by lrdj** [comment]
Hi Both:-)

Not sure where to find the _"the actual text of the response, not just the headers"_ but I've progressed a wee bit.

- Created new heroku node app using "dev" branch
- created new key for the bot github account

This got me a big chunky record of information. In there I sort of worked out that it was a 404. The problem was I put the github name of the bot account, not the blog account in the staticman url (user bug).

Fixing that by hand I can get the api to return a nice hash with stuff in it so I think that's working now.

So currently, when I submit a comment I get an token-related error:
"Error: Error during decryption (probably incorrect key). 
Original error: Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error"

(updated 5 Apr 00:26)

I added honeypot to the list of allowed fields [ "hp"]

Googling brought up this link: https://team-parallax.com/use-selfhosted-staticman-with-gitlab-2 which quotes "error:04099079"

They suggest looking for stray strings in the staticman.yml file, in particular having recaptcha string values when recaptcha is not activated. I replaced these values by "" and am no longer getting the RSA padding error.

So now things seem to be almost working... The pull requests appear and when I approve them they seem to appear in the comments page YAY! so that's good:-)

My next challenge is instead of the little modal status/confirmation box you have on your site I just get a "success: true" json message. I'm guessing there's a redirect_uri field I can pass that will releoad the post page but I'd quite like to replicate your experience.

Pointers welcome:-)

Best, Dug

**Comment by travisdowns** [comment]
> Not sure where to find the _"the actual text of the response, not just the headers"_ but I've progressed a wee bit.

In Firefox dev tools, you can see this by opening the "Network" console, clicking the POST request that shows when you click the submit button and then click "Response" in the pane on the right (I think you already did all except the last step). 

Screenshot:

![image](https://user-images.githubusercontent.com/2403521/78464057-26321600-76bb-11ea-8316-7e8daf302c77.png)

There you can see the json response sent back by staticman when there is an error.

**Comment by travisdowns** [comment]
> My next challenge is instead of the little modal status/confirmation box you have on your site I just get a "success: true" json message. I'm guessing there's a redirect_uri field I can pass that will releoad the post page but I'd quite like to replicate your experience.

You can check my source. 

Keys are the `js-form` class on the form [here](https://github.com/travisdowns/travisdowns.github.io/blob/9e74f08574bc8f57cc5094ce05332ec3b49c4cb9/_includes/comment_form.html#L1), and corresponding javascript [here](https://github.com/travisdowns/travisdowns.github.io/blob/9e74f08574bc8f57cc5094ce05332ec3b49c4cb9/assets/main.js#L6) which sets the submit function to do the javascript magic.

Note that if the user disables JS, this should still work, falling back to the action in the comment form itself (which opens another page, as you note: you can set the URL of this page in the staticman config, IIRC).

I didn't invent this, I just copied it from someone else (either spinningnumbers.org or Michael Rose's theme, I forget).

**Comment by alexwaibel** [comment]
It seems the original issue here has been resolved so I'm going to close this issue. Feel free to continue to ask any follow up questions here and I'll do my best to address them!
