### ISSUE TITLE
"Deploy to Heroku" button not functioning in the README when using Brave

### ISSUE THREAD

**Issue by mattkennedynz** [eduardoboucas/staticman#348]
Hey all—the "Deploy to Heroku" button isn't functioning in the README. It seems to redirect to [https://dashboard.heroku.com/new?template=](https://dashboard.heroku.com/new?template=) without building the Staticman repo.

For now I was able to clone the Staticman repo to my computer, then I successfully deployed the code to my Heroku app manually from there (after realizing that RSA_PRIVATE_KEY var requires quote marks around it).

**Comment by alexwaibel** [comment]
I am unable to replicate this issue. Which browser are you using?

**Comment by mattkennedynz** [comment]
You know, that is exactly it! I'm using Brave, but I just tried in Chrome and it _works_.

**Comment by alexwaibel** [comment]
Useful to know that Brave users may encounter issues. I'm not surprised as Brave seems to operate quite differently from most browsers. Thanks for the follow up! It'll help me debug any future issues like this. I'm going to mark this issue as closed, but feel free to ask any follow up questions here if you have them.
