### ISSUE TITLE
Question: Webhook address for Staticman at Heroku

### ISSUE THREAD

**Issue by willymcallister** [eduardoboucas/staticman#351]
What is the proper webhook address when I deploy Staticman at Heroku?

For the public instance the webhook was `https://api.staticman.net/v1/webhook`

For my instance I'm guessing `https://spinningnumbers-staticmandev2.herokuapp.com/v1/webhook/`, but I'm getting a 404 not found error.

While moving to Heroku I deleted the public staticman collaborator and only have my robot as a collaborator.

`2020-04-18T22:56:56.155851+00:00 heroku[router]: at=info method=POST path="/v1/webhook/" host=spinningnumbers-staticmandev2.herokuapp.com request_id=a8552a56-4182-415d-ba95-5cae432a7f07 fwd="140.82.115.241" dyno=web.1 connect=0ms service=6ms status=404 bytes=505 protocol=https
`

**Comment by willymcallister** [comment]
Solved... I removed the trailing `/` from the webhook URL.  Changed `v1/webhook/` to `v1/webhook` and the not-found problem cleared up. This mailhook provides two services: It deletes unneeded branches *and* it launches a notification email to people who have subscribed. This second feature isn't (yet) mentioned in the Staticman documentation for webhooks. Thanks to @travisdowns for spotting the flaw.

**Comment by travisdowns** [comment]
@willymcallister - glad it worked! Can I ask what documentation you followed? I might go ahead and set up the webhook itself.

I forgot that the webhook also sends mail (I don't have mailgun set up since it seems you need your own domain for that to work).

**Comment by willymcallister** [comment]
@travisdowns - I was clued in to the need for the webhook by [this post](https://www.gabescode.com/staticman/2019/01/04/staticman-comments-for-jekyll.html#webhook) from @gabeluci. The easy instructions are at the [mother ship](https://staticman.net/docs/webhooks). The intro doesn't mention notifications getting triggered, but they do. The url for the webhook changes from `https://api.staticman.net/v1/webhook` to `https://yourAppName.herokuapp.com/v1/webhook`, with no `/` at the end!

I'm working on my own exhaustive deployment instructions. I will link them here when they are ready.

**Comment by willymcallister** [comment]
Instructions for how to deploy an instance of Staticman at Heroku... https://spinningnumbers.org/a/staticman-heroku.html

This could benefit from peer review. I'm happy to entertain comments, answers to questions, or pull requests with improvements.

**Comment by alexwaibel** [comment]
@willymcallister thank you for your contributions on this repo. I've not had the time lately to work on this project and your help answering questions has been greatly appreciated!
