### ISSUE TITLE
Added bot account as collaborator, yet showing "Invitation not found"

### ISSUE THREAD

**Issue by devesh-anand** [eduardoboucas/staticman#353]
I deployed the heroku instance following the official documentation, and successfully added the bot account as collaborator in my blog repo, but whenever i check the "https://${bridge_app_name}.herokuapp.com/v2/connect/${github-username}/${blog-repo}"(with my appname and repo name), the message still shows "Invitation not found". I have rechecked the GITHUB_TOKEN and the rsa key. They are correct.

**Comment by devesh-anand** [comment]
Ok, so after reading the documentation for i don't know how many times, I realised that the "ok!" is displayed *only* once.

Now the issue is whenver I click the submit button, it shows:

> An error occured.
[MISSING_CONFIG_FIELDS]

I have checked the config.yml many times and i just cant find the issue. Here's the link to config.yml of my blog:
https://github.com/devesh-anand/devesh-anand.github.io/blob/master/_config.yml

**Comment by devesh-anand** [comment]
Ok, so finally the issue has been fixed and comments are working fine.

The real problem was the documentation itself.
This documentation:
https://travisdowns.github.io/blog/2020/02/05/now-with-comments.html
is badly out of shape. Specially if a newcomer tries it, chances are he/she will give up setting staticman comments on their static site.

I had to read documentations from different sources, had to go through github repos of some users using staticman.

@eduardoboucas please consider removing the above mentioned documentation from readme of staticman.

**Comment by willymcallister** [comment]
I started with Travis’s documentation and kept careful track of my adventure. Here is yet another Statesman at Heroku experience: https://spinningnumbers.org/a/staticman-heroku.html

**Comment by devesh-anand** [comment]
This was exactly what i needed. Detailed and precise. Thank you so much!

**Comment by devesh-anand** [comment]
@willymcallister Having an issue with automerging the requests send by the bot. Any suggestions?
I found automerge, but how do i add an "automerge" label from the pull requests from bot?

**Comment by willymcallister** [comment]
@devesh-anand -- I don't see moderation enabled in your staticman.yml file. Insert these lines:

```
  # Whether entries need to be approved before they are published to the main
  # branch. If set to `true`, a pull request will be created for your approval.
  # Otherwise, entries will be published to the main branch automatically.
  moderation: false
```

Be sure the "m" of "moderation" is indented 2 spaces (just like the "name:" field), so it is nested under "comments:". 

Look at my staticman.yml for an example. If you don't specify a t/f value for moderation the default is true.

**Comment by devesh-anand** [comment]
@willymcallister Thank you so much! Works perfectly now.

Just one final issue, mailgun free tier is free for just 3 months. Any alternatives?

**Comment by willymcallister** [comment]
@devesh-anand I don't know of an alternative to MailGun. I am on the lowest level "flex" plan that charges $0.0008 per message. My last bill was the first one to have a non-zero balance, and the charge was 4 cents ($0.04 USD).
