### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by zburgermeiszter** [eduardoboucas/staticman#37]
To help people who want to run it in a Docker container, I sent a [pull request](https://github.com/eduardoboucas/staticman/pull/36).

It is suggested to configure a Docker Hub automated build.

**Comment by eduardoboucas** [comment]
Thanks! I will have a look later today. 

Are you able to assist with that second part you mentioned?

**Comment by zburgermeiszter** [comment]
Created a new pull request. https://github.com/eduardoboucas/staticman/pull/38
Also wrote some documentation, and a proper configuration for the production and development environments.
Also included a link in the PR how to set up automated builds on Docker Hub.

**Comment by zburgermeiszter** [comment]
Thanks for accepting the PR.
When you happy with that you can close this issue.
