### ISSUE TITLE
npm start on windows gives "! was unexpected at this time."

### ISSUE THREAD

**Issue by mattumotu** [eduardoboucas/staticman#377]
I am running `npm start` on my windows box (after `npm install`) and I'm getting the following error:

> D:\git\staticman>npm start

> staticman@3.0.0 prestart D:\git\staticman
> if [ ! -d node_modules ]; then npm install; fi
! was unexpected at this time.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! staticman@3.0.0 prestart: `if [ ! -d node_modules ]; then npm install; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the staticman@3.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I believe this is due to the prestart script in packags.json not being valid in windows.
Removing this script seems to run ok, which is suitable on my dev box but not ideal for prod

**Comment by alexwaibel** [comment]
I believe you should be able to use the included docker configuration to run Staticman on Windows.
