### ISSUE TITLE
Config file generator and encryptor

### ISSUE THREAD

**Issue by zburgermeiszter** [eduardoboucas/staticman#39]
It would be useful to have a wizard form that requests all the config variables for the staticman.yml and at the end it encrypts the needed fields with the service public key.

As you mentioned there is going to be a defined set of config keys that need to be encrypted.
With this set and the pubkey and the submitted data, it is possible to generate the whole thing in the browser without the need for a service endpoint.

It would help newbies to begin with this service.

**Comment by eduardoboucas** [comment]
Not sure I understand what form this would take. Is it a standalone web app that generates a config file based on whatever people type in a series of input fields?

If so, that sounds like a cool idea, but I don't have the capacity to look into it. If you or someone else wants to have a go, then happy days!

**Comment by eduardoboucas** [comment]
I've added an endpoint that allows people to encrypt any piece of text: `https://api.staticman.net/v2/encrypt/{TEXT}`. I think this is as far as we'll go for now. Will add to the docs soon.

**Comment by eduardoboucas** [comment]
Added new page to the docs: https://staticman.net/docs/encryption

**Comment by zburgermeiszter** [comment]
Do you salt the encrypted content with any user/repository specific data?
Otherwise the users will be able to reuse each others API keys for 3rd party services.
