### ISSUE TITLE
trouble decrypting encrypted comment fields

### ISSUE THREAD

**Issue by infominer33** [eduardoboucas/staticman#390]
hey! I really love staticman, thanks for all the hard work to those maintaining it! 

I've enabled encryption for the e-mail field and message field to use as a regular contact form.. now I'm trying to decrypt my first contact message sent thru staticman.

first I tried:

`openssl rsautl -decrypt -in /home/bob/encrypted -out /home/bob/decrypted -inkey /home/bob/.ssh/id_bot_rsa`

outputs:
```
RSA operation error
139704754267456:error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error:../crypto/rsa/rsa_pk1.c:251:
139704754267456:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:491:
```

then I found this post by VincentTam about [Staticman's Encryption Mechanism](https://vincenttam.gitlab.io/post/2018-12-25-staticman-encryption-mechanism/) and try changing my decrypted message to base64 but getting a similar error

`cat encrypted | base64 -d | openssl rsautl -decrypt -oaep -out /home/bob/decrypted -inkey /home/bob/.ssh/id_bot_rsa`

outputs:
```
140543979599168:error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error:../crypto/rsa/rsa_oaep.c:262:
140543979599168:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:491:
```

I didn't realize it would be this hard, or I would have tried decrypting before I got my first submission to this contact form 😅

I plan to do this in python eventually.. so, I'm not married to this openssl method if you have a suggestion in a different direction.

any help appreciated

**Comment by infominer33** [comment]
Ok, trying again after finding RSA.js.. I copied it's contents to decrypt.js in the root of my staticman project folder (on the server where it's hosted) and modified that for this purpose:

```
const NodeRSA = require('node-rsa')
const key = new NodeRSA()
key.importKey('-----BEGIN RSA PRIVATE KEY-----\n Key found in config.production.json \n-----END RSA PRIVATE KEY-----', 'private');
const decrypted = key.decrypt('539c27a0e4b4bfc25f45b2254245wergdsa10803f725', 'utf8');
console.log('decrypted: ', decrypted); 
```

`node decrypt.js`

outputs:

```
/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:301
            throw Error('Error during decryption (probably incorrect key). Original error: ' + e);
            ^

Error: Error during decryption (probably incorrect key). Original error: Error: Incorrect data or key
    at NodeRSA.module.exports.NodeRSA.$$decryptKey (/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:301:19)
    at NodeRSA.module.exports.NodeRSA.decrypt (/home/bob/staticman/node_modules/node-rsa/src/NodeRSA.js:249:21)
    at Object.<anonymous> (/home/bob/staticman/decrypt.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

While it says probably incorrect key or data, but I've verified both, multiple times.

**Comment by infominer33** [comment]
oh... well, I guess I was sorely mistaken about what I was doing...

Unless I'm, yet again, mistaken, this setting in staticman config hashes the e-mail and the message, which is not a reversible action... which leads me to wonder.

```
  transforms:
    email: md5
    message: md5
```

If that's the case, then the form asks for an e-mail address simply to make sure the user enters an e-mail, or is supposed to be used in conjunction with mailgun so you get the email address in a message sent you via mail?

**Comment by infominer33** [comment]
sigh.... https://github.com/eduardoboucas/staticman/issues/358 I don't suppose there's any server side logging?

**Comment by hispanic** [comment]
@infominer33 Sorry, but the logging is minimal-to-nonexistent. I was going to respond earlier that the result of the transform is a one-way hash that can't be reversed, but then you referenced that "Staticman's Encryption Mechanism" article and you made me doubt.

**Comment by mocza** [comment]
Hi, 

I keep getting a similar "oaep decoding error" as above in my browser console when I hit submit on a comment: 
_responseJSON: Object { success: false, rawError: "Error: Error during decryption (probably incorrect key). Original error: Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error" }

I generated my RSA private key using:

`ssh-keygen -m PEM -t rsa -b 4096 -C "staticman key" -f ~/.ssh/staticman_key`

and I'm running my staticman instance on Heroku with RSA_PRIVATE_KEY config var set as:

`heroku config:add --app staticman-instance-name "RSA_PRIVATE_KEY=$(cat ~/.ssh/staticman_key | tr -d '\n')"`

My reCaptcha secret key was encrypted by my staticman instance using below URL form and has been populated in staticman.yml and _config.yml: 
https://${bridge_app_name}.herokuapp.com/v2/encrypt/{$recaptcha-secret}
  
What am I missing?

**Comment by VincentTam** [comment]
@mocza The output of

    cat ~/.ssh/staticman_key | tr -d '\n'

lacks trailing `\n` as the 2nd part `tr -d '\n'` removed all newlines, including the trailing one.  It seems that your API isn't happy about that.

When I was testing <span>#</span>219 three years ago, its author advised me to use a modern code editor to replace all occurrences of the newline character `\n` with the string `\n`.  (You may search the hidden discussion for the "missing RSA").

However, in Heroku deployment, that didn't work.  I used

    heroku config:set RSA_PRIVATE_KEY="$(cat key.pem)"

in my [API setup guide](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/) written three years ago before the creation of the GitHub App authorization method.

Recently, I've found an easier method in <span>#</span>402: just copy the contents of the PEM file and paste to the right text area for `RSA_PRIVATE_KEY` through Heroku's online dashboard.

I suggest you upgrade to v3.

**Comment by zxdawn** [comment]
@mocza Hi, how did you fix that problem? I met the same one ...
