### ISSUE TITLE
500 Internal server error.

### ISSUE THREAD

**Issue by taxilly** [eduardoboucas/staticman#40]
Hey, I keep getting 500 Internal server error for some reason. I've got an odd case where I'm using two repositories for my site; since I wanted to use plugins that aren't allowed with the `--safe` flag that github-pages uses for Jekyll. So I'm not sure if that's the issue. Basically my `movw-0x16` repo is where all the site data is, I then build the site and push that to twentytwoo.github.io.

I've gotten the staticmanapp set up as a collaborator and I checked to see if I was declaring anything twice in my _config.yml, but nope; so I'm unsure as what to do now.

Also, I get redirected to `https://api.staticman.net/v1/entry/twentytwoo/movw-0x16/master` on send, yet it displays nothing but `{}`.

Here's my _config.yml:
https://github.com/twentytwoo/movw-0x16/blob/master/_config.yml
And the page with the form:
https://github.com/twentytwoo/movw-0x16/blob/master/_layouts/post.html

**Comment by eduardoboucas** [comment]
In your config file, `requiredFields` isn't indented properly, as it's outside the scope of the `staticman` object. This seems to be the problem.

Let me know if that does the trick.

**Comment by taxilly** [comment]
I feel stupid now, that was it, thanks.

**Comment by eduardoboucas** [comment]
Don't. It's easy to miss these things with YAML. Plus, better error handling from Staticman would probably help.
