### ISSUE TITLE
Staticman support for OneDev devops platform

### ISSUE THREAD

**Issue by arthef** [eduardoboucas/staticman#422]
At the moment Staticman supports GitHub and GitLab. It would be very useful to have also support for OneDev: https://github.com/theonedev/onedev
which is free, self-hosted alternative to both above.

I am willing to sponsor implementation for this feature.

**Comment by arthef** [comment]
For anybody interested I have setup a bounty for the implementation: https://www.bountysource.com/issues/99526689-staticman-support-for-onedev-devops-platform

**Comment by KN4CK3R** [comment]
I have added a PR which adds support for OneDev. As OneDev lacks some needed API endpoints this Pull Request needs to merged first:
- [x] https://code.onedev.io/projects/onedev-server/pulls/28 (merged)

**Comment by arthef** [comment]
The PR was not accepted yet but it all works for me. Here is a link to a [Staticman repository](https://1dev.just-4.dev/staticman) with working code in both stand-alone mode and Docker container.
Thank you for the implementation.
