### ISSUE TITLE
MISSING_CONFIG_BLOCK error on post

### ISSUE THREAD

**Issue by sjdodge123** [eduardoboucas/staticman#432]
Hi,

I have been getting a message when sending to a new staticman deployment that I have been unable to resolve. I can provide the steps that I have taken over the last several hours..

On post of this form
`<form method="post" action="https://staticman-chaochao.herokuapp.com/v2/entry/sjdodge123/chaochao/main/maps">
                    <input name="fields[message]" type="text" class="form-control" id="comment-form-message" placeholder="message" required="">
                    <input name="fields[name]" type="text" class="form-control" id="comment-form-name" placeholder="Your name (required)" required="">
                    <button class="col-12 btn btn-primary" id="comment-form-submit">Submit</button>
                </form>`

 I get the following response 

`{"success":false,"message":"Error whilst parsing Staticman config file","rawError":{"_smErrorCode":"MISSING_CONFIG_BLOCK"},"errorCode":"MISSING_CONFIG_BLOCK"}`

I am trying from my repo where I have a sample staticman.yml defined here [https://github.com/sjdodge123/chaochao](https://github.com/sjdodge123/chaochao)

My heroku app log states this

`2021-08-28T03:28:22.022617+00:00 heroku[router]: at=info method=POST path="/v2/entry/sjdodge123/chaochao/main/maps" host=staticman-chaochao.herokuapp.com request_id=90c2b45b-fc74-4a11-a66a-e619bc6e6c14 fwd="137.83.202.112" dyno=web.1 connect=0ms service=83ms status=500 bytes=495 protocol=https`

Side note, staticman is great and I love all of the hard work yall do!

**Comment by hispanic** [comment]
In your `action` value ("https://staticman-chaochao.herokuapp.com/v2/entry/sjdodge123/chaochao/main/maps"), you specify "maps" as the `property`, but your staticman.yml does not appear to contain such a property. In it, this is what I see:

```
# Name of the property. You can have multiple properties with completely
# different config blocks for different sections of your site.
# For example, you can have one property to handle comment submission and
# another one to handle posts.
comments:
  # (*) REQUIRED
  #
  # Names of the fields the form is allowed to submit. If a field that is
  # not here is part of the request, an error will be thrown.
  allowedFields: ["name", "email", "url", "message", "replying_to_uid"]

  # (*) REQUIRED
  ...
```

Try changing "maps" to "comments". More info here: https://staticman.net/docs/getting-started.html#step-4-hook-up-your-forms

**Comment by sjdodge123** [comment]
> In your `action` value ("https://staticman-chaochao.herokuapp.com/v2/entry/sjdodge123/chaochao/main/maps"), you specify "maps" as the `property`, but your staticman.yml does not appear to contain such a property. In it, this is what I see:
> 
> ```
> # Name of the property. You can have multiple properties with completely
> # different config blocks for different sections of your site.
> # For example, you can have one property to handle comment submission and
> # another one to handle posts.
> comments:
>   # (*) REQUIRED
>   #
>   # Names of the fields the form is allowed to submit. If a field that is
>   # not here is part of the request, an error will be thrown.
>   allowedFields: ["name", "email", "url", "message", "replying_to_uid"]
> 
>   # (*) REQUIRED
>   ...
> ```
> 
> Try changing "maps" to "comments". More info here: https://staticman.net/docs/getting-started.html#step-4-hook-up-your-forms

excellent catch and thanks for your reply. You have no idea how many hours I sunk into trying to fix this and it was that simple.. oof

**Comment by hispanic** [comment]
Welcome! At least you can rest well knowing that you've documented a gotcha' for the benefit of future generations.
