### ISSUE TITLE
"Error" when adding staticmanapp as collaborator

### ISSUE THREAD

**Issue by taxilly** [eduardoboucas/staticman#45]
I ran `https://api.staticman.net/v1/connect/velddev/agdg.me` to get staticmanapp to become a collab., all I get is `Error`, I even forked it and used my own username to auth it, but it still just prompts `Error`. So staticmanapp is just pending as of now.

I have staticman working on my own site, and I never had an issue at this stage with it; so I don't understand what's up with it at the moment :(

<img src="https://u.nya.is/rakorm.png">

**Comment by eduardoboucas** [comment]
I've pushed some major changes to the API last night, I wonder if that might be causing the issue. Will have a look shortly.

**Comment by eduardoboucas** [comment]
Can you test now, please?

**Comment by taxilly** [comment]
Yup! It works now, whatever you did fixed it :)

**Comment by eduardoboucas** [comment]
The endpoint in GitHub API we're using is in preview mode, and apparently something changed very recently. Anyway, fixed!

Closing via #46.
