### ISSUE TITLE
Heroku Application Error

### ISSUE THREAD

**Issue by danPixl** [eduardoboucas/staticman#53]
Your main server is down -- it doesn't respond to

- new posts
- adding it as a collaborator 

Heroku responds with
`Application error`
`An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.`

**Comment by danPixl** [comment]
Paging @eduardoboucas

**Comment by eduardoboucas** [comment]
Oops, sorry about that. This should be fixed now, but please do reopen if you see this happening again.

**Comment by danPixl** [comment]
Thanks!

**Comment by matthew-brett** [comment]
I am getting this error " An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details." when accessing `https://api.staticman.net/v2/connect/matthew-brett/asterisk-blog`, after adding `staticmanapp` as a collaborator.

**Comment by GeorgeChiggins** [comment]
> I am getting this error " An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details." when accessing `https://api.staticman.net/v2/connect/matthew-brett/asterisk-blog`, after adding `staticmanapp` as a collaborator.

yeah same

**Comment by dtsn** [comment]
Getting the error again today
