### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by danPixl** [eduardoboucas/staticman#57]
Whenever I attempt to post (the way an end-user would), the api.staticman.net website responds with

{}

The submission doesn't get created.
Thanks in advanced.

**Comment by eduardoboucas** [comment]
Link to the repository, please?

**Comment by danPixl** [comment]
Sure thing! https://github.com/ColumbineSpace/News
There's also a website at http://news.columbine.space .

**Comment by danPixl** [comment]
@eduardoboucas

**Comment by eduardoboucas** [comment]
Sorry, will be with you soon.

**Comment by eduardoboucas** [comment]
@danPixl Can you please check now?

**Comment by danPixl** [comment]
It works now, thanks so much for your help.

**Comment by eduardoboucas** [comment]
No problem, thanks for flagging! There was a bug in the API that caused an issue with sites without moderation. That has been fixed now. 🎉
