### ISSUE TITLE
Demo URLs

### ISSUE THREAD

**Issue by cweiske** [eduardoboucas/staticman#6]
It'd be nice to see websites where this is actually used.

**Comment by eduardoboucas** [comment]
You can see it in action [on my website](https://eduardoboucas.com/), and the repository is [here](https://github.com/eduardoboucas/eduardoboucas.github.io).

I'd be nice to add a section to the README with a list of sites using it, but perhaps once we have a few more?

**Comment by eduardoboucas** [comment]
There's also [this](http://popcorn.staticman.net) and a screencast showing how that was made: https://eduardoboucas.com/blog/2016/08/10/staticman.html

**Comment by cweiske** [comment]
I wouldn't wait until the list is larger than x.

**Comment by mmistakes** [comment]
I'm using Staticman to power comments on my personal site [Made Mistakes](https://mademistakes.com/) ([repo](https://github.com/mmistakes/made-mistakes-jekyll)), along with adding it as an option to a [Jekyll theme](https://github.com/mmistakes/minimal-mistakes) I maintain.

**Comment by eduardoboucas** [comment]
Thanks. Added [a section to the README](https://github.com/eduardoboucas/staticman#sites-using-staticman). Keep 'em coming!

**Comment by taxilly** [comment]
I'm using it on [startpages.cf](http://startpages.cf/), to allow users to submit startpages and [movw-0x16.cf](http://movw-0x16.cf) to send comments.

**Comment by eduardoboucas** [comment]
Thanks, @twentytwoo. Do you mind adding those to the README (including a link to the source repository, if public) and creating a PR?

I will close this issue in favour of asking people to PR will their own sites.
