### ISSUE TITLE
Are Notifications sent before or after merging pull request?

### ISSUE THREAD

**Issue by zongren** [eduardoboucas/staticman#64]
I set the moderation to be true

**Comment by dancwilliams** [comment]
I have been trying to test a few different scenarios this evening. The behavior I am seeing is that the notification does not go out until you perform the merge. Also, notifications are sent to visitors who request notifications even if you do not merge their comment.

**Comment by eduardoboucas** [comment]
> The behavior I am seeing is that the notification does not go out until you perform the merge

This is correct and it's intended behaviour. You don't want people receiving an email about a comment hasn't (and might not ever be) published.

> Also, notifications are sent to visitors who request notifications even if you do not merge their comment.

This isn't really intended behaviour, but I'm a bit torn on it actually. Even if your comment isn't approved, you should still have the right to be notified of other people's comments.

What are your thoughts?

**Comment by zongren** [comment]
> Also, notifications are sent to visitors who request notifications even if you do not merge their comment.

I don't think this is necessary.
If someone leaves an unrelated or violated message, I don't want him to receive further notifications.

**Comment by dancwilliams** [comment]
If you express that you want to be notified of new comments you should receive those notifications no matter the status of your comment. 

I asked some people sitting around me what they would expect and this is the behavior they expected. Probably just need to document all the different flow scenarios so people are aware.

**Comment by dancwilliams** [comment]
I see your point as well zongren.  If you got some bots leaving comments you did not merge, but they still receive notifications, it could eat into your mailgun calls and lead to real $$$.

**Comment by eduardoboucas** [comment]
Very good points raised here. To avoid duplication, let's move the conversation to #42.
