### ISSUE TITLE
{} and 500 response

### ISSUE THREAD

**Issue by BladeFireLight** [eduardoboucas/staticman#72]
I setup two test repos. on on an account with uppercase in the path and one with out. both with the example config for v2. 
when trying to post I get a page with { } with a resonse of 500, and no PR

https://github.com/bladefirelight2/staticmantest

```
<form action="https://api.staticman.net/v2/entry/bladefirelight2/staticmantest/master/comments" method="POST">
   <input name="options[origin]" type="hidden" value="http://localhost:4000/test.html"> 
  <input name="options[slug]" type="hidden" value="">
  <label><input name="fields[name]" type="text">Name</label>
  <label><input name="fields[email]" type="email">E-mail</label>
  <label><textarea name="fields[message]"></textarea>Message</label>
  
  <button type="submit">Go!</button>
</form>

```

https://github.com/BladeFireLight/staticmantest

```
<form action="https://api.staticman.net/v2/entry/BladeFireLight/staticmantest/master/comments" method="POST">
   <input name="options[origin]" type="hidden" value="http://localhost:4000/test.html"> 
  <input name="options[slug]" type="hidden" value="">
  <label><input name="fields[name]" type="text">Name</label>
  <label><input name="fields[email]" type="email">E-mail</label>
  <label><textarea name="fields[message]"></textarea>Message</label>
  
  <button type="submit">Go!</button>
</form>

```

**Comment by BladeFireLight** [comment]
It looks like event when notifications are set to false in the example config the sub field like API key cant be present or you get the 500 error

**Comment by eduardoboucas** [comment]
Thanks for reporting, I'll have a look. So is it working for you now?

**Comment by BladeFireLight** [comment]
Yes. mirrored your sites config as to what fields were in use and then my test worked.

Thanks.

**Comment by BladeFireLight** [comment]
ok, I got a valid account with mailgun and used your form to encrypt the key and domain. 

I get the PR notification but no emails on replies.

**Comment by willymcallister** [comment]
BladeFireLight - I'm also getting {} 500 when I click submit. Can you provide some details about how you achieved a fix ("mirrored your site's config"). My web site is at https://willymcallister.github.io/electrical-engineering. The comment form at the bottom of posts is currently un-styled. Staticmanapp is a collaborator, and I got back a cheery OK! from the connect request. Thanks for any advice.

**Comment by eduardoboucas** [comment]
The email notifications feature is still not fully stable, that's why you won't find proper documentation on it. If this is still an issue for any of you, could you please confirm if:

- You're using the public instance of Staticman or a private one
- You're using the Staticman Mailgun account or your own one
  - If the latter, do you see Mailing Lists being created under your account (you should see one for each thread), and email addresses being added?

Thanks

**Comment by eduardoboucas** [comment]
I'd like to move all the feedback around email notifications to #42 — could you please post any updates there?

Thanks!
