### ISSUE TITLE
Transform support downcase

### ISSUE THREAD

**Issue by BladeFireLight** [eduardoboucas/staticman#74]
the email field is your example for md5 hash, and it's commondly used for gravitar.  Gravitar only supports lowercase email addresses.  
Can you add support for downcase transforms (or watever java calls it)

yaml would be something like this

```
transforms:
    email: ["downcase", "md5"]
```

**Comment by eduardoboucas** [comment]
The transform itself should be simple to implement, but I believe the logic around transforms will need some work in order to support more than one transform per field. I'll look into it.

**Comment by atomicwrites** [comment]
@eduardoboucas My JS is pretty rusty but I'd be willing to give this a shot if you think it's a good idea. I would also like this for my site.

**Comment by atomicwrites** [comment]
Unless I'm missing something this would just require iterating over each item in the array and applying the transforms one at a time, no?

**Comment by alexwaibel** [comment]
This appears to have been implemented. Closing.
