### ISSUE TITLE
What are all the options?

### ISSUE THREAD

**Issue by simonv3** [eduardoboucas/staticman#76]
I see references to options to submit in the documentation, but I'm not sure what they all are.

Is there a difference between options and fields? 

If I supply `{options.slug}` in my `filename` field in `staticman.yml`, do I have to actually pass an options.slug to the submission or is this automatically generated?

**Comment by eduardoboucas** [comment]
Both `options` and `fields` need to be passed as part of the request, with the only difference being the former will not be added to the data file and the latter will. Hope this helps!

**Comment by simonv3** [comment]
Ah, that makes sense. Thanks @eduardoboucas
