### ISSUE TITLE
Editing a file

### ISSUE THREAD

**Issue by simonv3** [eduardoboucas/staticman#77]
Is it possible for staticman to edit an existing file when it submits content?

When submitting to what would be the same file (as the file name is predefined by the form that gets submitted) I get the following error:
```
{"code":422,"status":"Unprocessable Entity","message":"{\"message\":\"Invalid request.\\n\\n\\\"sha\\\" wasn't supplied.\",\"documentation_url\":\"https://developer.github.com/v3/repos/contents/\"}"}
```

Which looks like it's a GitHub error complaining about the `sha` value not being supplied to the API?

**Comment by eduardoboucas** [comment]
It's not possible to edit existing files at the moment.

**Comment by simonv3** [comment]
What would need to change to make that possible? Or is it pretty fundamentally hard?

**Comment by matbrgz** [comment]
Any ideia where start?
