### ISSUE TITLE
let commitMessage accept placeholders.

### ISSUE THREAD

**Issue by simonv3** [eduardoboucas/staticman#79]
So that we could give more details in the title of the PR from staticman. 

Ex.

```
commitMessage: "{fields.title}"
```

**Comment by bnvk** [comment]
A big +100 to @simonv3 suggestion for this. The current subject lines make GH pull request email impossible to keep track of / make any sense of.

**Comment by eduardoboucas** [comment]
Thanks for this. I'll look into adding this feature.

**Comment by eduardoboucas** [comment]
@simonv3 @bnvk This has been implemented in #80 and deployed to the test API instance.

Could you help testing it, to make sure it's working as expected? All you need to do is replace `api.staticman.net` with `dev.staticman.net` in your form URLs.

Thanks! 💪

**Comment by simonv3** [comment]
Awesome, that looks like it worked @eduardoboucas! Thanks so much for the quick turnaround on that. This will make our notifications much easier to parse.

**Comment by eduardoboucas** [comment]
Deployed to live. Thanks!
