### ISSUE TITLE
Delete branches created by Staticman

### ISSUE THREAD

**Issue by eduardoboucas** [eduardoboucas/staticman#8]
Currently, branches created by Staticman need to be deleted manually, which is a bit of a pain.

We could add a webhook that would allow us to detect every time a pull request created by the bot is either merged or closed, and we could delete the associated branch at that point.

Should we ask people to manually set up this webhook, or should we set it up for them when they run `connect`? I like how the second option is automated, but isn't it a bit intrusive as well?

Any thoughts welcome.

EDIT: Actually, ignore the second option, as we'd need admin access to the repos in order to create the hooks, which we obviously don't want.

**Comment by eduardoboucas** [comment]
This has been added in #10. Will leave the issue open until docs are in place.

**Comment by quicoto** [comment]
Don't quite understand how to add the webhook so I'll wait for the nice docs 😄

**Comment by mmistakes** [comment]
Excellent. This works great @eduardoboucas!
@quicoto I was able to set it up by:
1. Going to my GitHub repo, clicking **Settings**, then **Webhooks & services**
2. Click **add webhook** button and add `https://api.staticman.net/v1/webhook` to Payload URL, leave content type `application/json`, choose "select individual events" and check **Push** and **Active**.

After all that anytime I merge or close a Staticman pull request the branch is auto-deleted.

Hope this helps!

**Comment by eduardoboucas** [comment]
Perfect, @mmistakes! Thanks for sharing that info.

The only thing I'd add is that the best event to use is **Pull request**, as shown in the screenshot below. This sends the least amount of data to Staticman, which avoids hammering the instance with too many requests.

I'm trying to find the time to add a proper docs page to the website where all this information will go.

![screen shot 2016-08-17 at 09 32 38](https://cloud.githubusercontent.com/assets/4162329/17729759/9cbb9af4-645d-11e6-9b70-7d1cfb477b2f.png)

**Comment by mmistakes** [comment]
Oops. **Pull request** is what I meant, not Push.

**Comment by eduardoboucas** [comment]
Documentation added here: https://staticman.net/docs/webhooks

Closing! 🎉

**Comment by quicoto** [comment]
Sorry for the late reply. I've tested the instructions, it works great.

**Comment by OmarEmaraDev** [comment]
Should we change `v1` to `v2` in the Payload URL since staticman is now on version 2 or should it be left intact?

**Comment by diogo-almeida** [comment]
@OmarSquircleArt, as of Nov 20, 2018, I need to use v1 in the Payload URL on my own instance of staticman (which is version 2) in order for the webhook to work.
