### ISSUE TITLE
Add pingback support

### ISSUE THREAD

**Issue by zburgermeiszter** [eduardoboucas/staticman#84]
In wordpress yoh can receive notifications when someone mentions your blogpost.
Here's an interesting post about [how to implement pingback for Jekyll](http://blog.mlindgren.ca/entry/2015/01/17/how-to-manually-send-a-pingback/)

[Another](http://www.phonk.net/Gedachten/pingback)

The pingback endpoint could be the Staticman, which is defined in a meta tag, then when someone mention the post on a blog which sends pingbacks, Staticman would simply process it just like a comment.
Easy :)

Sending a pingback is a separate story which has to be implemented in the build script, and won't be supported for those jekyll sites that use github's own builder feature as it does not support plugins.

**Comment by zburgermeiszter** [comment]
[Another](http://www.phonk.net/Gedachten/pingback)

**Comment by eduardoboucas** [comment]
Sounds good. But like I said in another thread, I'd like to get our existing features to a stable place and improve documentation in general before thinking of adding new features.

Something worth investigating in the future, though.

Thanks!
