### ISSUE TITLE
Add auto-generated fields to documentation

### ISSUE THREAD

**Issue by dansmith65** [eduardoboucas/staticman#85]
I'm working on getting staticman setup on my blog now and was surprised to find that `_id`, `date`, and `timestamp` were all added to [a submission](https://github.com/dansmith65/dansmith65.github.io/pull/3/files) by default. When I noticed this, I went to https://staticman.net/docs/configuration to look for an explanation but couldn't find one. I'd suggest adding this info to the top of that page, so the various references to `@id` and `@timestamp` further down that page make sense once you get to them.

I had considered adding this info myself and submitting it as proposal via a pull request, but I don't really understand what values are added, or why. For example:

1. Why does `_id` start with an underscore when `timestamp` does not?
2. Was `timestamp` added because I referenced it in the [filename config](https://github.com/dansmith65/dansmith65.github.io/blob/b33116a738cff8a45cccad6ac3fb9ac282028a3c/staticman.yml#L35)?
3. Why was `date` added? I can't find any reason to explain that. I [disabled the generatedFields](https://github.com/dansmith65/dansmith65.github.io/blob/b33116a738cff8a45cccad6ac3fb9ac282028a3c/staticman.yml#L45) option, but that only changed the format from a number to an iso8601 string.

**Comment by eduardoboucas** [comment]
`_id` is prefixed with an underscore because it's an internal field, and it's added automatically to every entry.

As for the rest of the fields, they shouldn't be added automatically, only when you add them to `generatedFields`. I'll look into this.
