### ISSUE TITLE
Add available types and options to generatedFields documentation

### ISSUE THREAD

**Issue by dansmith65** [eduardoboucas/staticman#86]
I think https://staticman.net/docs/configuration#generatedFields should state the available types and options, for example:

* date options format:
  * "timestamp": milliseconds since 1970/01/01
  * "timestamp-seconds": seconds since 1970/01/01
  * "iso8601": date as a string like: '2017-03-03T23:28:14.272Z'

**Comment by eduardoboucas** [comment]
I agree, but this is essentially a duplicate of #56. If you don't mind, I'll close this and move the discussion there.
