### ISSUE TITLE
Added unintended attributes in data files.

### ISSUE THREAD

**Issue by nakoo** [eduardoboucas/staticman#92]
I did not intend to insert timestamp and layout attributes. 
But it is sometimes added my comment data files abnormality. Can I know why it is occurred?

You can see the example like this:
[https://github.com/mmistakes/made-mistakes-jekyll/blob/670807a0f8d41e15320c7913497f79c4af72aaf1/src/_data/comments/improving-jekyll-static-comments/comment-1488553821919.yml](https://github.com/mmistakes/made-mistakes-jekyll/blob/670807a0f8d41e15320c7913497f79c4af72aaf1/src/_data/comments/improving-jekyll-static-comments/comment-1488553821919.yml)

It looks someone else have same problem.
[https://github.com/eduardoboucas/staticman/issues/85](https://github.com/eduardoboucas/staticman/issues/85)
[https://github.com/eduardoboucas/staticman/issues/91](https://github.com/eduardoboucas/staticman/issues/91)

**Comment by eduardoboucas** [comment]
The only fields Staticman may automatically add to an entry are `_id` and `_parent`. Any other fields must be coming from elsewhere, perhaps from the theme you're using.
