### ISSUE TITLE
Support for hexo

### ISSUE THREAD

**Issue by skandasoft** [eduardoboucas/staticman#93]
Would this solution work for hexo/ can this be a plugin for hexo blogging framework

**Comment by eduardoboucas** [comment]
Staticman can work with any static site generator. All it does is receive form submissions and convert the data into data files, pushing them to a GitHub repository. You can see an example implementation with Jekyll [here](https://github.com/eduardoboucas/popcorn) and [here](https://github.com/eduardoboucas/staticman-recaptcha), and an example implementation with Hugo [here](https://github.com/eduardoboucas/hugo-plus-staticman). The same principles would apply for Hexo or any other static site generator, as long as you have a way of re-generating your site every time a new commit is made.

Hope this helps. Feel free to reopen the issue if you have any other questions.
