### ISSUE TITLE
frontmatter layout: overwrites fields value supplied with post

### ISSUE THREAD

**Issue by simonv3** [eduardoboucas/staticman#97]
I don't know if something has changed in staticman that might cause this, but I'm seeing that the field that generates the layout for our posts gets ignored. 

While we have a field in our form that submits [layout: "jobs" (html)](https://github.com/opensourcedesign/jobs/blob/gh-pages/job-form.html#L23) and the layout is in our [`allowedFields`](https://github.com/opensourcedesign/jobs/blob/gh-pages/staticman.yml#L13). Yet the [resulting PR](https://github.com/opensourcedesign/jobs/pull/191/files) still has it as a `post`.

Any thoughts on what could be going wrong here?

**Comment by eduardoboucas** [comment]
That's very odd. We're not introducing any field called `layout`, so not sure what's causing that. I'll have a proper look tomorrow.

**Comment by eduardoboucas** [comment]
I have just tested submitting your form twice: once using a local copy of your site and my local instance of the Staticman API, a second one using the live site and live API. In both cases the PR is coming through with the correct value for `layout` (see [PR 1](https://github.com/opensourcedesign/jobs/pull/192) and [PR 2](https://github.com/opensourcedesign/jobs/pull/193)).

Closing. Feel free to reopen if you're still seeing the issue.

**Comment by simonv3** [comment]
@eduardoboucas - did you change anything or is this a glitch somewhere else I should put some effort into tracking down? I can't reproduce it right now either. Thanks for looking into it!

**Comment by eduardoboucas** [comment]
I haven't changed anything, so it must be coming from somewhere else.
